IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedSelectReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedSelectReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedSelectReportTicketsViewItem

(
  @TicketID int
)
AS
  SET NOCOUNT OFF;
  SELECT
    [TicketID],
    [ProductName],
    [ReportedVersion],
    [SolvedVersion],
    [GroupName],
    [TicketTypeName],
    [UserName],
    [Status],
    [StatusPosition],
    [SeverityPosition],
    [IsClosed],
    [Severity],
    [TicketNumber],
    [IsVisibleOnPortal],
    [IsKnowledgeBase],
    [ReportedVersionID],
    [SolvedVersionID],
    [ProductID],
    [GroupID],
    [UserID],
    [TicketStatusID],
    [TicketTypeID],
    [TicketSeverityID],
    [OrganizationID],
    [Name],
    [ParentID],
    [ModifierID],
    [CreatorID],
    [DateModified],
    [DateCreated],
    [DateClosed],
    [CloserID],
    [DaysClosed],
    [MinutesClosed],
    [DaysOpened],
    [MinutesOpened],
    [CloserName],
    [CreatorName],
    [ModifierName],
    [HoursSpent],
    [Tags],
    [SlaViolationTime],
    [SlaWarningTime],
    [SlaViolationHours],
    [SlaWarningHours],
    [MinsSinceCreated],
    [DaysSinceCreated],
    [MinsSinceModified],
    [DaysSinceModified],
    [Contacts],
    [Customers],
    [SlaViolationTimeClosed],
    [SlaViolationLastAction],
    [SlaViolationInitialResponse],
    [SlaWarningTimeClosed],
    [SlaWarningLastAction],
    [SlaWarningInitialResponse],
    [NeedsIndexing],
    [SlaViolationDate],
    [SlaWarningDate],
    [TicketSource],
    [ForumCategory],
    [CategoryName],
    [CreatorEmail],
    [ModifierEmail],
    [KnowledgeBaseCategoryID],
    [KnowledgeBaseCategoryName],
    [KnowledgeBaseParentCategoryName],
    [DueDate],
    [SalesForceID],
    [DateModifiedBySalesForceSync],
    [DateModifiedByJiraSync],
    [JiraID],
    [SyncWithJira],
    [JiraKey],
    [JiraLinkURL],
    [JiraStatus],
    [ChildTicketCount],
    [RelatedTicketCount],
    [MinutesToInitialResponse],
    [DayOfWeekCreated],
    [HourOfDayCreated]
  FROM [dbo].[ReportTicketsView]
  WHERE ([TicketID] = @TicketID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedInsertReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedInsertReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedInsertReportTicketsViewItem

(
  @TicketID int,
  @ProductName varchar(255),
  @ReportedVersion varchar(50),
  @SolvedVersion varchar(50),
  @GroupName varchar(255),
  @TicketTypeName varchar(255),
  @UserName varchar(201),
  @Status varchar(255),
  @StatusPosition int,
  @SeverityPosition int,
  @IsClosed bit,
  @Severity varchar(255),
  @TicketNumber int,
  @IsVisibleOnPortal bit,
  @IsKnowledgeBase bit,
  @ReportedVersionID int,
  @SolvedVersionID int,
  @ProductID int,
  @GroupID int,
  @UserID int,
  @TicketStatusID int,
  @TicketTypeID int,
  @TicketSeverityID int,
  @OrganizationID int,
  @Name varchar(255),
  @ParentID int,
  @ModifierID int,
  @CreatorID int,
  @DateModified datetime,
  @DateCreated datetime,
  @DateClosed datetime,
  @CloserID int,
  @DaysClosed int,
  @MinutesClosed int,
  @DaysOpened int,
  @MinutesOpened int,
  @CloserName varchar(201),
  @CreatorName varchar(201),
  @ModifierName varchar(201),
  @HoursSpent decimal,
  @Tags varchar(8000),
  @SlaViolationTime int,
  @SlaWarningTime int,
  @SlaViolationHours decimal,
  @SlaWarningHours decimal,
  @MinsSinceCreated int,
  @DaysSinceCreated int,
  @MinsSinceModified int,
  @DaysSinceModified int,
  @Contacts varchar(8000),
  @Customers varchar(8000),
  @SlaViolationTimeClosed datetime,
  @SlaViolationLastAction datetime,
  @SlaViolationInitialResponse datetime,
  @SlaWarningTimeClosed datetime,
  @SlaWarningLastAction datetime,
  @SlaWarningInitialResponse datetime,
  @NeedsIndexing bit,
  @SlaViolationDate datetime,
  @SlaWarningDate datetime,
  @TicketSource varchar(50),
  @ForumCategory int,
  @CategoryName nvarchar(100),
  @CreatorEmail varchar(1024),
  @ModifierEmail varchar(1024),
  @KnowledgeBaseCategoryID int,
  @KnowledgeBaseCategoryName nvarchar(100),
  @KnowledgeBaseParentCategoryName nvarchar(100),
  @DueDate datetime,
  @SalesForceID varchar(8000),
  @DateModifiedBySalesForceSync datetime,
  @DateModifiedByJiraSync datetime,
  @JiraID int,
  @SyncWithJira bit,
  @JiraKey varchar(8000),
  @JiraLinkURL varchar(8000),
  @JiraStatus varchar(8000),
  @ChildTicketCount int,
  @RelatedTicketCount int,
  @MinutesToInitialResponse int,
  @DayOfWeekCreated nvarchar(30),
  @HourOfDayCreated int,
  @Identity int OUT
)
AS
  SET NOCOUNT OFF;
  INSERT INTO [dbo].[ReportTicketsView]
(
    [TicketID],
    [ProductName],
    [ReportedVersion],
    [SolvedVersion],
    [GroupName],
    [TicketTypeName],
    [UserName],
    [Status],
    [StatusPosition],
    [SeverityPosition],
    [IsClosed],
    [Severity],
    [TicketNumber],
    [IsVisibleOnPortal],
    [IsKnowledgeBase],
    [ReportedVersionID],
    [SolvedVersionID],
    [ProductID],
    [GroupID],
    [UserID],
    [TicketStatusID],
    [TicketTypeID],
    [TicketSeverityID],
    [OrganizationID],
    [Name],
    [ParentID],
    [ModifierID],
    [CreatorID],
    [DateModified],
    [DateCreated],
    [DateClosed],
    [CloserID],
    [DaysClosed],
    [MinutesClosed],
    [DaysOpened],
    [MinutesOpened],
    [CloserName],
    [CreatorName],
    [ModifierName],
    [HoursSpent],
    [Tags],
    [SlaViolationTime],
    [SlaWarningTime],
    [SlaViolationHours],
    [SlaWarningHours],
    [MinsSinceCreated],
    [DaysSinceCreated],
    [MinsSinceModified],
    [DaysSinceModified],
    [Contacts],
    [Customers],
    [SlaViolationTimeClosed],
    [SlaViolationLastAction],
    [SlaViolationInitialResponse],
    [SlaWarningTimeClosed],
    [SlaWarningLastAction],
    [SlaWarningInitialResponse],
    [NeedsIndexing],
    [SlaViolationDate],
    [SlaWarningDate],
    [TicketSource],
    [ForumCategory],
    [CategoryName],
    [CreatorEmail],
    [ModifierEmail],
    [KnowledgeBaseCategoryID],
    [KnowledgeBaseCategoryName],
    [KnowledgeBaseParentCategoryName],
    [DueDate],
    [SalesForceID],
    [DateModifiedBySalesForceSync],
    [DateModifiedByJiraSync],
    [JiraID],
    [SyncWithJira],
    [JiraKey],
    [JiraLinkURL],
    [JiraStatus],
    [ChildTicketCount],
    [RelatedTicketCount],
    [MinutesToInitialResponse],
    [DayOfWeekCreated],
    [HourOfDayCreated])
  VALUES (
    @TicketID,
    @ProductName,
    @ReportedVersion,
    @SolvedVersion,
    @GroupName,
    @TicketTypeName,
    @UserName,
    @Status,
    @StatusPosition,
    @SeverityPosition,
    @IsClosed,
    @Severity,
    @TicketNumber,
    @IsVisibleOnPortal,
    @IsKnowledgeBase,
    @ReportedVersionID,
    @SolvedVersionID,
    @ProductID,
    @GroupID,
    @UserID,
    @TicketStatusID,
    @TicketTypeID,
    @TicketSeverityID,
    @OrganizationID,
    @Name,
    @ParentID,
    @ModifierID,
    @CreatorID,
    @DateModified,
    @DateCreated,
    @DateClosed,
    @CloserID,
    @DaysClosed,
    @MinutesClosed,
    @DaysOpened,
    @MinutesOpened,
    @CloserName,
    @CreatorName,
    @ModifierName,
    @HoursSpent,
    @Tags,
    @SlaViolationTime,
    @SlaWarningTime,
    @SlaViolationHours,
    @SlaWarningHours,
    @MinsSinceCreated,
    @DaysSinceCreated,
    @MinsSinceModified,
    @DaysSinceModified,
    @Contacts,
    @Customers,
    @SlaViolationTimeClosed,
    @SlaViolationLastAction,
    @SlaViolationInitialResponse,
    @SlaWarningTimeClosed,
    @SlaWarningLastAction,
    @SlaWarningInitialResponse,
    @NeedsIndexing,
    @SlaViolationDate,
    @SlaWarningDate,
    @TicketSource,
    @ForumCategory,
    @CategoryName,
    @CreatorEmail,
    @ModifierEmail,
    @KnowledgeBaseCategoryID,
    @KnowledgeBaseCategoryName,
    @KnowledgeBaseParentCategoryName,
    @DueDate,
    @SalesForceID,
    @DateModifiedBySalesForceSync,
    @DateModifiedByJiraSync,
    @JiraID,
    @SyncWithJira,
    @JiraKey,
    @JiraLinkURL,
    @JiraStatus,
    @ChildTicketCount,
    @RelatedTicketCount,
    @MinutesToInitialResponse,
    @DayOfWeekCreated,
    @HourOfDayCreated)

SET @Identity = SCOPE_IDENTITY()
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedUpdateReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedUpdateReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedUpdateReportTicketsViewItem

(
  @TicketID int,
  @ProductName varchar(255),
  @ReportedVersion varchar(50),
  @SolvedVersion varchar(50),
  @GroupName varchar(255),
  @TicketTypeName varchar(255),
  @UserName varchar(201),
  @Status varchar(255),
  @StatusPosition int,
  @SeverityPosition int,
  @IsClosed bit,
  @Severity varchar(255),
  @TicketNumber int,
  @IsVisibleOnPortal bit,
  @IsKnowledgeBase bit,
  @ReportedVersionID int,
  @SolvedVersionID int,
  @ProductID int,
  @GroupID int,
  @UserID int,
  @TicketStatusID int,
  @TicketTypeID int,
  @TicketSeverityID int,
  @OrganizationID int,
  @Name varchar(255),
  @ParentID int,
  @ModifierID int,
  @DateModified datetime,
  @DateClosed datetime,
  @CloserID int,
  @DaysClosed int,
  @MinutesClosed int,
  @DaysOpened int,
  @MinutesOpened int,
  @CloserName varchar(201),
  @CreatorName varchar(201),
  @ModifierName varchar(201),
  @HoursSpent decimal,
  @Tags varchar(8000),
  @SlaViolationTime int,
  @SlaWarningTime int,
  @SlaViolationHours decimal,
  @SlaWarningHours decimal,
  @MinsSinceCreated int,
  @DaysSinceCreated int,
  @MinsSinceModified int,
  @DaysSinceModified int,
  @Contacts varchar(8000),
  @Customers varchar(8000),
  @SlaViolationTimeClosed datetime,
  @SlaViolationLastAction datetime,
  @SlaViolationInitialResponse datetime,
  @SlaWarningTimeClosed datetime,
  @SlaWarningLastAction datetime,
  @SlaWarningInitialResponse datetime,
  @NeedsIndexing bit,
  @SlaViolationDate datetime,
  @SlaWarningDate datetime,
  @TicketSource varchar(50),
  @ForumCategory int,
  @CategoryName nvarchar(100),
  @CreatorEmail varchar(1024),
  @ModifierEmail varchar(1024),
  @KnowledgeBaseCategoryID int,
  @KnowledgeBaseCategoryName nvarchar(100),
  @KnowledgeBaseParentCategoryName nvarchar(100),
  @DueDate datetime,
  @SalesForceID varchar(8000),
  @DateModifiedBySalesForceSync datetime,
  @DateModifiedByJiraSync datetime,
  @JiraID int,
  @SyncWithJira bit,
  @JiraKey varchar(8000),
  @JiraLinkURL varchar(8000),
  @JiraStatus varchar(8000),
  @ChildTicketCount int,
  @RelatedTicketCount int,
  @MinutesToInitialResponse int,
  @DayOfWeekCreated nvarchar(30),
  @HourOfDayCreated int
)
AS
  SET NOCOUNT OFF;
  UPDATE [dbo].[ReportTicketsView]
  SET
    [ProductName] = @ProductName,
    [ReportedVersion] = @ReportedVersion,
    [SolvedVersion] = @SolvedVersion,
    [GroupName] = @GroupName,
    [TicketTypeName] = @TicketTypeName,
    [UserName] = @UserName,
    [Status] = @Status,
    [StatusPosition] = @StatusPosition,
    [SeverityPosition] = @SeverityPosition,
    [IsClosed] = @IsClosed,
    [Severity] = @Severity,
    [TicketNumber] = @TicketNumber,
    [IsVisibleOnPortal] = @IsVisibleOnPortal,
    [IsKnowledgeBase] = @IsKnowledgeBase,
    [ReportedVersionID] = @ReportedVersionID,
    [SolvedVersionID] = @SolvedVersionID,
    [ProductID] = @ProductID,
    [GroupID] = @GroupID,
    [UserID] = @UserID,
    [TicketStatusID] = @TicketStatusID,
    [TicketTypeID] = @TicketTypeID,
    [TicketSeverityID] = @TicketSeverityID,
    [OrganizationID] = @OrganizationID,
    [Name] = @Name,
    [ParentID] = @ParentID,
    [ModifierID] = @ModifierID,
    [DateModified] = @DateModified,
    [DateClosed] = @DateClosed,
    [CloserID] = @CloserID,
    [DaysClosed] = @DaysClosed,
    [MinutesClosed] = @MinutesClosed,
    [DaysOpened] = @DaysOpened,
    [MinutesOpened] = @MinutesOpened,
    [CloserName] = @CloserName,
    [CreatorName] = @CreatorName,
    [ModifierName] = @ModifierName,
    [HoursSpent] = @HoursSpent,
    [Tags] = @Tags,
    [SlaViolationTime] = @SlaViolationTime,
    [SlaWarningTime] = @SlaWarningTime,
    [SlaViolationHours] = @SlaViolationHours,
    [SlaWarningHours] = @SlaWarningHours,
    [MinsSinceCreated] = @MinsSinceCreated,
    [DaysSinceCreated] = @DaysSinceCreated,
    [MinsSinceModified] = @MinsSinceModified,
    [DaysSinceModified] = @DaysSinceModified,
    [Contacts] = @Contacts,
    [Customers] = @Customers,
    [SlaViolationTimeClosed] = @SlaViolationTimeClosed,
    [SlaViolationLastAction] = @SlaViolationLastAction,
    [SlaViolationInitialResponse] = @SlaViolationInitialResponse,
    [SlaWarningTimeClosed] = @SlaWarningTimeClosed,
    [SlaWarningLastAction] = @SlaWarningLastAction,
    [SlaWarningInitialResponse] = @SlaWarningInitialResponse,
    [NeedsIndexing] = @NeedsIndexing,
    [SlaViolationDate] = @SlaViolationDate,
    [SlaWarningDate] = @SlaWarningDate,
    [TicketSource] = @TicketSource,
    [ForumCategory] = @ForumCategory,
    [CategoryName] = @CategoryName,
    [CreatorEmail] = @CreatorEmail,
    [ModifierEmail] = @ModifierEmail,
    [KnowledgeBaseCategoryID] = @KnowledgeBaseCategoryID,
    [KnowledgeBaseCategoryName] = @KnowledgeBaseCategoryName,
    [KnowledgeBaseParentCategoryName] = @KnowledgeBaseParentCategoryName,
    [DueDate] = @DueDate,
    [SalesForceID] = @SalesForceID,
    [DateModifiedBySalesForceSync] = @DateModifiedBySalesForceSync,
    [DateModifiedByJiraSync] = @DateModifiedByJiraSync,
    [JiraID] = @JiraID,
    [SyncWithJira] = @SyncWithJira,
    [JiraKey] = @JiraKey,
    [JiraLinkURL] = @JiraLinkURL,
    [JiraStatus] = @JiraStatus,
    [ChildTicketCount] = @ChildTicketCount,
    [RelatedTicketCount] = @RelatedTicketCount,
    [MinutesToInitialResponse] = @MinutesToInitialResponse,
    [DayOfWeekCreated] = @DayOfWeekCreated,
    [HourOfDayCreated] = @HourOfDayCreated
  WHERE ([TicketID] = @TicketID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedDeleteReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedDeleteReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedDeleteReportTicketsViewItem

(
  @TicketID int
)
AS
  SET NOCOUNT OFF;
  DELETE FROM [dbo].[ReportTicketsView]
  WHERE ([TicketID] = @TicketID)
GO


IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedSelectReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedSelectReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedSelectReportTicketsViewItem

(
  @TicketID int
)
AS
  SET NOCOUNT OFF;
  SELECT
    [TicketID],
    [ProductName],
    [ReportedVersion],
    [SolvedVersion],
    [GroupName],
    [TicketTypeName],
    [UserName],
    [Status],
    [StatusPosition],
    [SeverityPosition],
    [IsClosed],
    [Severity],
    [TicketNumber],
    [IsVisibleOnPortal],
    [IsKnowledgeBase],
    [ReportedVersionID],
    [SolvedVersionID],
    [ProductID],
    [GroupID],
    [UserID],
    [TicketStatusID],
    [TicketTypeID],
    [TicketSeverityID],
    [OrganizationID],
    [Name],
    [ParentID],
    [ModifierID],
    [CreatorID],
    [DateModified],
    [DateCreated],
    [DateClosed],
    [CloserID],
    [DaysClosed],
    [MinutesClosed],
    [DaysOpened],
    [MinutesOpened],
    [CloserName],
    [CreatorName],
    [ModifierName],
    [HoursSpent],
    [Tags],
    [SlaViolationTime],
    [SlaWarningTime],
    [SlaViolationHours],
    [SlaWarningHours],
    [MinsSinceCreated],
    [DaysSinceCreated],
    [MinsSinceModified],
    [DaysSinceModified],
    [Contacts],
    [Customers],
    [SlaViolationTimeClosed],
    [SlaViolationLastAction],
    [SlaViolationInitialResponse],
    [SlaWarningTimeClosed],
    [SlaWarningLastAction],
    [SlaWarningInitialResponse],
    [NeedsIndexing],
    [SlaViolationDate],
    [SlaWarningDate],
    [TicketSource],
    [ForumCategory],
    [CategoryName],
    [CreatorEmail],
    [ModifierEmail],
    [KnowledgeBaseCategoryID],
    [KnowledgeBaseCategoryName],
    [KnowledgeBaseParentCategoryName],
    [DueDate],
    [SalesForceID],
    [DateModifiedBySalesForceSync],
    [DateModifiedByJiraSync],
    [JiraID],
    [SyncWithJira],
    [JiraKey],
    [JiraLinkURL],
    [JiraStatus],
    [ChildTicketCount],
    [RelatedTicketCount],
    [MinutesToInitialResponse],
    [DayOfWeekCreated],
    [HourOfDayCreated]
  FROM [dbo].[ReportTicketsView]
  WHERE ([TicketID] = @TicketID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedInsertReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedInsertReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedInsertReportTicketsViewItem

(
  @TicketID int,
  @ProductName varchar(255),
  @ReportedVersion varchar(50),
  @SolvedVersion varchar(50),
  @GroupName varchar(255),
  @TicketTypeName varchar(255),
  @UserName varchar(201),
  @Status varchar(255),
  @StatusPosition int,
  @SeverityPosition int,
  @IsClosed bit,
  @Severity varchar(255),
  @TicketNumber int,
  @IsVisibleOnPortal bit,
  @IsKnowledgeBase bit,
  @ReportedVersionID int,
  @SolvedVersionID int,
  @ProductID int,
  @GroupID int,
  @UserID int,
  @TicketStatusID int,
  @TicketTypeID int,
  @TicketSeverityID int,
  @OrganizationID int,
  @Name varchar(255),
  @ParentID int,
  @ModifierID int,
  @CreatorID int,
  @DateModified datetime,
  @DateCreated datetime,
  @DateClosed datetime,
  @CloserID int,
  @DaysClosed int,
  @MinutesClosed int,
  @DaysOpened int,
  @MinutesOpened int,
  @CloserName varchar(201),
  @CreatorName varchar(201),
  @ModifierName varchar(201),
  @HoursSpent decimal,
  @Tags varchar(8000),
  @SlaViolationTime int,
  @SlaWarningTime int,
  @SlaViolationHours decimal,
  @SlaWarningHours decimal,
  @MinsSinceCreated int,
  @DaysSinceCreated int,
  @MinsSinceModified int,
  @DaysSinceModified int,
  @Contacts varchar(8000),
  @Customers varchar(8000),
  @SlaViolationTimeClosed datetime,
  @SlaViolationLastAction datetime,
  @SlaViolationInitialResponse datetime,
  @SlaWarningTimeClosed datetime,
  @SlaWarningLastAction datetime,
  @SlaWarningInitialResponse datetime,
  @NeedsIndexing bit,
  @SlaViolationDate datetime,
  @SlaWarningDate datetime,
  @TicketSource varchar(50),
  @ForumCategory int,
  @CategoryName nvarchar(100),
  @CreatorEmail varchar(1024),
  @ModifierEmail varchar(1024),
  @KnowledgeBaseCategoryID int,
  @KnowledgeBaseCategoryName nvarchar(100),
  @KnowledgeBaseParentCategoryName nvarchar(100),
  @DueDate datetime,
  @SalesForceID varchar(8000),
  @DateModifiedBySalesForceSync datetime,
  @DateModifiedByJiraSync datetime,
  @JiraID int,
  @SyncWithJira bit,
  @JiraKey varchar(8000),
  @JiraLinkURL varchar(8000),
  @JiraStatus varchar(8000),
  @ChildTicketCount int,
  @RelatedTicketCount int,
  @MinutesToInitialResponse int,
  @DayOfWeekCreated nvarchar(30),
  @HourOfDayCreated int,
  @Identity int OUT
)
AS
  SET NOCOUNT OFF;
  INSERT INTO [dbo].[ReportTicketsView]
  (
    [TicketID],
    [ProductName],
    [ReportedVersion],
    [SolvedVersion],
    [GroupName],
    [TicketTypeName],
    [UserName],
    [Status],
    [StatusPosition],
    [SeverityPosition],
    [IsClosed],
    [Severity],
    [TicketNumber],
    [IsVisibleOnPortal],
    [IsKnowledgeBase],
    [ReportedVersionID],
    [SolvedVersionID],
    [ProductID],
    [GroupID],
    [UserID],
    [TicketStatusID],
    [TicketTypeID],
    [TicketSeverityID],
    [OrganizationID],
    [Name],
    [ParentID],
    [ModifierID],
    [CreatorID],
    [DateModified],
    [DateCreated],
    [DateClosed],
    [CloserID],
    [DaysClosed],
    [MinutesClosed],
    [DaysOpened],
    [MinutesOpened],
    [CloserName],
    [CreatorName],
    [ModifierName],
    [HoursSpent],
    [Tags],
    [SlaViolationTime],
    [SlaWarningTime],
    [SlaViolationHours],
    [SlaWarningHours],
    [MinsSinceCreated],
    [DaysSinceCreated],
    [MinsSinceModified],
    [DaysSinceModified],
    [Contacts],
    [Customers],
    [SlaViolationTimeClosed],
    [SlaViolationLastAction],
    [SlaViolationInitialResponse],
    [SlaWarningTimeClosed],
    [SlaWarningLastAction],
    [SlaWarningInitialResponse],
    [NeedsIndexing],
    [SlaViolationDate],
    [SlaWarningDate],
    [TicketSource],
    [ForumCategory],
    [CategoryName],
    [CreatorEmail],
    [ModifierEmail],
    [KnowledgeBaseCategoryID],
    [KnowledgeBaseCategoryName],
    [KnowledgeBaseParentCategoryName],
    [DueDate],
    [SalesForceID],
    [DateModifiedBySalesForceSync],
    [DateModifiedByJiraSync],
    [JiraID],
    [SyncWithJira],
    [JiraKey],
    [JiraLinkURL],
    [JiraStatus],
    [ChildTicketCount],
    [RelatedTicketCount],
    [MinutesToInitialResponse],
    [DayOfWeekCreated],
    [HourOfDayCreated])
  VALUES (
    @TicketID,
    @ProductName,
    @ReportedVersion,
    @SolvedVersion,
    @GroupName,
    @TicketTypeName,
    @UserName,
    @Status,
    @StatusPosition,
    @SeverityPosition,
    @IsClosed,
    @Severity,
    @TicketNumber,
    @IsVisibleOnPortal,
    @IsKnowledgeBase,
    @ReportedVersionID,
    @SolvedVersionID,
    @ProductID,
    @GroupID,
    @UserID,
    @TicketStatusID,
    @TicketTypeID,
    @TicketSeverityID,
    @OrganizationID,
    @Name,
    @ParentID,
    @ModifierID,
    @CreatorID,
    @DateModified,
    @DateCreated,
    @DateClosed,
    @CloserID,
    @DaysClosed,
    @MinutesClosed,
    @DaysOpened,
    @MinutesOpened,
    @CloserName,
    @CreatorName,
    @ModifierName,
    @HoursSpent,
    @Tags,
    @SlaViolationTime,
    @SlaWarningTime,
    @SlaViolationHours,
    @SlaWarningHours,
    @MinsSinceCreated,
    @DaysSinceCreated,
    @MinsSinceModified,
    @DaysSinceModified,
    @Contacts,
    @Customers,
    @SlaViolationTimeClosed,
    @SlaViolationLastAction,
    @SlaViolationInitialResponse,
    @SlaWarningTimeClosed,
    @SlaWarningLastAction,
    @SlaWarningInitialResponse,
    @NeedsIndexing,
    @SlaViolationDate,
    @SlaWarningDate,
    @TicketSource,
    @ForumCategory,
    @CategoryName,
    @CreatorEmail,
    @ModifierEmail,
    @KnowledgeBaseCategoryID,
    @KnowledgeBaseCategoryName,
    @KnowledgeBaseParentCategoryName,
    @DueDate,
    @SalesForceID,
    @DateModifiedBySalesForceSync,
    @DateModifiedByJiraSync,
    @JiraID,
    @SyncWithJira,
    @JiraKey,
    @JiraLinkURL,
    @JiraStatus,
    @ChildTicketCount,
    @RelatedTicketCount,
    @MinutesToInitialResponse,
    @DayOfWeekCreated,
    @HourOfDayCreated)

SET @Identity = SCOPE_IDENTITY()
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedUpdateReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedUpdateReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedUpdateReportTicketsViewItem

(
  @TicketID int,
  @ProductName varchar(255),
  @ReportedVersion varchar(50),
  @SolvedVersion varchar(50),
  @GroupName varchar(255),
  @TicketTypeName varchar(255),
  @UserName varchar(201),
  @Status varchar(255),
  @StatusPosition int,
  @SeverityPosition int,
  @IsClosed bit,
  @Severity varchar(255),
  @TicketNumber int,
  @IsVisibleOnPortal bit,
  @IsKnowledgeBase bit,
  @ReportedVersionID int,
  @SolvedVersionID int,
  @ProductID int,
  @GroupID int,
  @UserID int,
  @TicketStatusID int,
  @TicketTypeID int,
  @TicketSeverityID int,
  @OrganizationID int,
  @Name varchar(255),
  @ParentID int,
  @ModifierID int,
  @DateModified datetime,
  @DateClosed datetime,
  @CloserID int,
  @DaysClosed int,
  @MinutesClosed int,
  @DaysOpened int,
  @MinutesOpened int,
  @CloserName varchar(201),
  @CreatorName varchar(201),
  @ModifierName varchar(201),
  @HoursSpent decimal,
  @Tags varchar(8000),
  @SlaViolationTime int,
  @SlaWarningTime int,
  @SlaViolationHours decimal,
  @SlaWarningHours decimal,
  @MinsSinceCreated int,
  @DaysSinceCreated int,
  @MinsSinceModified int,
  @DaysSinceModified int,
  @Contacts varchar(8000),
  @Customers varchar(8000),
  @SlaViolationTimeClosed datetime,
  @SlaViolationLastAction datetime,
  @SlaViolationInitialResponse datetime,
  @SlaWarningTimeClosed datetime,
  @SlaWarningLastAction datetime,
  @SlaWarningInitialResponse datetime,
  @NeedsIndexing bit,
  @SlaViolationDate datetime,
  @SlaWarningDate datetime,
  @TicketSource varchar(50),
  @ForumCategory int,
  @CategoryName nvarchar(100),
  @CreatorEmail varchar(1024),
  @ModifierEmail varchar(1024),
  @KnowledgeBaseCategoryID int,
  @KnowledgeBaseCategoryName nvarchar(100),
  @KnowledgeBaseParentCategoryName nvarchar(100),
  @DueDate datetime,
  @SalesForceID varchar(8000),
  @DateModifiedBySalesForceSync datetime,
  @DateModifiedByJiraSync datetime,
  @JiraID int,
  @SyncWithJira bit,
  @JiraKey varchar(8000),
  @JiraLinkURL varchar(8000),
  @JiraStatus varchar(8000),
  @ChildTicketCount int,
  @RelatedTicketCount int,
  @MinutesToInitialResponse int,
  @DayOfWeekCreated nvarchar(30),
  @HourOfDayCreated int
)
AS
  SET NOCOUNT OFF;
  UPDATE [dbo].[ReportTicketsView]
  SET
    [ProductName] = @ProductName,
    [ReportedVersion] = @ReportedVersion,
    [SolvedVersion] = @SolvedVersion,
    [GroupName] = @GroupName,
    [TicketTypeName] = @TicketTypeName,
    [UserName] = @UserName,
    [Status] = @Status,
    [StatusPosition] = @StatusPosition,
    [SeverityPosition] = @SeverityPosition,
    [IsClosed] = @IsClosed,
    [Severity] = @Severity,
    [TicketNumber] = @TicketNumber,
    [IsVisibleOnPortal] = @IsVisibleOnPortal,
    [IsKnowledgeBase] = @IsKnowledgeBase,
    [ReportedVersionID] = @ReportedVersionID,
    [SolvedVersionID] = @SolvedVersionID,
    [ProductID] = @ProductID,
    [GroupID] = @GroupID,
    [UserID] = @UserID,
    [TicketStatusID] = @TicketStatusID,
    [TicketTypeID] = @TicketTypeID,
    [TicketSeverityID] = @TicketSeverityID,
    [OrganizationID] = @OrganizationID,
    [Name] = @Name,
    [ParentID] = @ParentID,
    [ModifierID] = @ModifierID,
    [DateModified] = @DateModified,
    [DateClosed] = @DateClosed,
    [CloserID] = @CloserID,
    [DaysClosed] = @DaysClosed,
    [MinutesClosed] = @MinutesClosed,
    [DaysOpened] = @DaysOpened,
    [MinutesOpened] = @MinutesOpened,
    [CloserName] = @CloserName,
    [CreatorName] = @CreatorName,
    [ModifierName] = @ModifierName,
    [HoursSpent] = @HoursSpent,
    [Tags] = @Tags,
    [SlaViolationTime] = @SlaViolationTime,
    [SlaWarningTime] = @SlaWarningTime,
    [SlaViolationHours] = @SlaViolationHours,
    [SlaWarningHours] = @SlaWarningHours,
    [MinsSinceCreated] = @MinsSinceCreated,
    [DaysSinceCreated] = @DaysSinceCreated,
    [MinsSinceModified] = @MinsSinceModified,
    [DaysSinceModified] = @DaysSinceModified,
    [Contacts] = @Contacts,
    [Customers] = @Customers,
    [SlaViolationTimeClosed] = @SlaViolationTimeClosed,
    [SlaViolationLastAction] = @SlaViolationLastAction,
    [SlaViolationInitialResponse] = @SlaViolationInitialResponse,
    [SlaWarningTimeClosed] = @SlaWarningTimeClosed,
    [SlaWarningLastAction] = @SlaWarningLastAction,
    [SlaWarningInitialResponse] = @SlaWarningInitialResponse,
    [NeedsIndexing] = @NeedsIndexing,
    [SlaViolationDate] = @SlaViolationDate,
    [SlaWarningDate] = @SlaWarningDate,
    [TicketSource] = @TicketSource,
    [ForumCategory] = @ForumCategory,
    [CategoryName] = @CategoryName,
    [CreatorEmail] = @CreatorEmail,
    [ModifierEmail] = @ModifierEmail,
    [KnowledgeBaseCategoryID] = @KnowledgeBaseCategoryID,
    [KnowledgeBaseCategoryName] = @KnowledgeBaseCategoryName,
    [KnowledgeBaseParentCategoryName] = @KnowledgeBaseParentCategoryName,
    [DueDate] = @DueDate,
    [SalesForceID] = @SalesForceID,
    [DateModifiedBySalesForceSync] = @DateModifiedBySalesForceSync,
    [DateModifiedByJiraSync] = @DateModifiedByJiraSync,
    [JiraID] = @JiraID,
    [SyncWithJira] = @SyncWithJira,
    [JiraKey] = @JiraKey,
    [JiraLinkURL] = @JiraLinkURL,
    [JiraStatus] = @JiraStatus,
    [ChildTicketCount] = @ChildTicketCount,
    [RelatedTicketCount] = @RelatedTicketCount,
    [MinutesToInitialResponse] = @MinutesToInitialResponse,
    [DayOfWeekCreated] = @DayOfWeekCreated,
    [HourOfDayCreated] = @HourOfDayCreated
  WHERE ([TicketID] = @TicketID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedDeleteReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedDeleteReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedDeleteReportTicketsViewItem

(
  @TicketID int
)
AS
  SET NOCOUNT OFF;
  DELETE FROM [dbo].[ReportTicketsView]
  WHERE ([TicketID] = @TicketID)
GO


IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedSelectReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedSelectReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedSelectReportTicketsViewItem

(
  @TicketID int
)
AS
  SET NOCOUNT OFF;
  SELECT
    [TicketID],
    [ProductName],
    [ReportedVersion],
    [SolvedVersion],
    [GroupName],
    [TicketTypeName],
    [UserName],
    [Status],
    [StatusPosition],
    [SeverityPosition],
    [IsClosed],
    [Severity],
    [TicketNumber],
    [IsVisibleOnPortal],
    [IsKnowledgeBase],
    [ReportedVersionID],
    [SolvedVersionID],
    [ProductID],
    [GroupID],
    [UserID],
    [TicketStatusID],
    [TicketTypeID],
    [TicketSeverityID],
    [OrganizationID],
    [Name],
    [ParentID],
    [ModifierID],
    [CreatorID],
    [DateModified],
    [DateCreated],
    [DateClosed],
    [CloserID],
    [DaysClosed],
    [MinutesClosed],
    [DaysOpened],
    [MinutesOpened],
    [CloserName],
    [CreatorName],
    [ModifierName],
    [HoursSpent],
    [Tags],
    [SlaViolationTime],
    [SlaWarningTime],
    [SlaViolationHours],
    [SlaWarningHours],
    [MinsSinceCreated],
    [DaysSinceCreated],
    [MinsSinceModified],
    [DaysSinceModified],
    [Contacts],
    [Customers],
    [SlaViolationTimeClosed],
    [SlaViolationLastAction],
    [SlaViolationInitialResponse],
    [SlaWarningTimeClosed],
    [SlaWarningLastAction],
    [SlaWarningInitialResponse],
    [NeedsIndexing],
    [SlaViolationDate],
    [SlaWarningDate],
    [TicketSource],
    [ForumCategory],
    [CategoryName],
    [CreatorEmail],
    [ModifierEmail],
    [KnowledgeBaseCategoryID],
    [KnowledgeBaseCategoryName],
    [KnowledgeBaseParentCategoryName],
    [DueDate],
    [SalesForceID],
    [DateModifiedBySalesForceSync],
    [DateModifiedByJiraSync],
    [JiraID],
    [SyncWithJira],
    [JiraKey],
    [JiraLinkURL],
    [JiraStatus],
    [ChildTicketCount],
    [RelatedTicketCount],
    [MinutesToInitialResponse],
    [DayOfWeekCreated],
    [HourOfDayCreated]
  FROM [dbo].[ReportTicketsView]
  WHERE ([TicketID] = @TicketID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedInsertReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedInsertReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedInsertReportTicketsViewItem

(
  @TicketID int,
  @ProductName varchar(255),
  @ReportedVersion varchar(50),
  @SolvedVersion varchar(50),
  @GroupName varchar(255),
  @TicketTypeName varchar(255),
  @UserName varchar(201),
  @Status varchar(255),
  @StatusPosition int,
  @SeverityPosition int,
  @IsClosed bit,
  @Severity varchar(255),
  @TicketNumber int,
  @IsVisibleOnPortal bit,
  @IsKnowledgeBase bit,
  @ReportedVersionID int,
  @SolvedVersionID int,
  @ProductID int,
  @GroupID int,
  @UserID int,
  @TicketStatusID int,
  @TicketTypeID int,
  @TicketSeverityID int,
  @OrganizationID int,
  @Name varchar(255),
  @ParentID int,
  @ModifierID int,
  @CreatorID int,
  @DateModified datetime,
  @DateCreated datetime,
  @DateClosed datetime,
  @CloserID int,
  @DaysClosed int,
  @MinutesClosed int,
  @DaysOpened int,
  @MinutesOpened int,
  @CloserName varchar(201),
  @CreatorName varchar(201),
  @ModifierName varchar(201),
  @HoursSpent decimal,
  @Tags varchar(8000),
  @SlaViolationTime int,
  @SlaWarningTime int,
  @SlaViolationHours decimal,
  @SlaWarningHours decimal,
  @MinsSinceCreated int,
  @DaysSinceCreated int,
  @MinsSinceModified int,
  @DaysSinceModified int,
  @Contacts varchar(8000),
  @Customers varchar(8000),
  @SlaViolationTimeClosed datetime,
  @SlaViolationLastAction datetime,
  @SlaViolationInitialResponse datetime,
  @SlaWarningTimeClosed datetime,
  @SlaWarningLastAction datetime,
  @SlaWarningInitialResponse datetime,
  @NeedsIndexing bit,
  @SlaViolationDate datetime,
  @SlaWarningDate datetime,
  @TicketSource varchar(50),
  @ForumCategory int,
  @CategoryName nvarchar(100),
  @CreatorEmail varchar(1024),
  @ModifierEmail varchar(1024),
  @KnowledgeBaseCategoryID int,
  @KnowledgeBaseCategoryName nvarchar(100),
  @KnowledgeBaseParentCategoryName nvarchar(100),
  @DueDate datetime,
  @SalesForceID varchar(8000),
  @DateModifiedBySalesForceSync datetime,
  @DateModifiedByJiraSync datetime,
  @JiraID int,
  @SyncWithJira bit,
  @JiraKey varchar(8000),
  @JiraLinkURL varchar(8000),
  @JiraStatus varchar(8000),
  @ChildTicketCount int,
  @RelatedTicketCount int,
  @MinutesToInitialResponse int,
  @DayOfWeekCreated nvarchar(30),
  @HourOfDayCreated int,
  @Identity int OUT
)
AS
  SET NOCOUNT OFF;
  INSERT INTO [dbo].[ReportTicketsView]
  (
    [TicketID],
    [ProductName],
    [ReportedVersion],
    [SolvedVersion],
    [GroupName],
    [TicketTypeName],
    [UserName],
    [Status],
    [StatusPosition],
    [SeverityPosition],
    [IsClosed],
    [Severity],
    [TicketNumber],
    [IsVisibleOnPortal],
    [IsKnowledgeBase],
    [ReportedVersionID],
    [SolvedVersionID],
    [ProductID],
    [GroupID],
    [UserID],
    [TicketStatusID],
    [TicketTypeID],
    [TicketSeverityID],
    [OrganizationID],
    [Name],
    [ParentID],
    [ModifierID],
    [CreatorID],
    [DateModified],
    [DateCreated],
    [DateClosed],
    [CloserID],
    [DaysClosed],
    [MinutesClosed],
    [DaysOpened],
    [MinutesOpened],
    [CloserName],
    [CreatorName],
    [ModifierName],
    [HoursSpent],
    [Tags],
    [SlaViolationTime],
    [SlaWarningTime],
    [SlaViolationHours],
    [SlaWarningHours],
    [MinsSinceCreated],
    [DaysSinceCreated],
    [MinsSinceModified],
    [DaysSinceModified],
    [Contacts],
    [Customers],
    [SlaViolationTimeClosed],
    [SlaViolationLastAction],
    [SlaViolationInitialResponse],
    [SlaWarningTimeClosed],
    [SlaWarningLastAction],
    [SlaWarningInitialResponse],
    [NeedsIndexing],
    [SlaViolationDate],
    [SlaWarningDate],
    [TicketSource],
    [ForumCategory],
    [CategoryName],
    [CreatorEmail],
    [ModifierEmail],
    [KnowledgeBaseCategoryID],
    [KnowledgeBaseCategoryName],
    [KnowledgeBaseParentCategoryName],
    [DueDate],
    [SalesForceID],
    [DateModifiedBySalesForceSync],
    [DateModifiedByJiraSync],
    [JiraID],
    [SyncWithJira],
    [JiraKey],
    [JiraLinkURL],
    [JiraStatus],
    [ChildTicketCount],
    [RelatedTicketCount],
    [MinutesToInitialResponse],
    [DayOfWeekCreated],
    [HourOfDayCreated])
  VALUES (
    @TicketID,
    @ProductName,
    @ReportedVersion,
    @SolvedVersion,
    @GroupName,
    @TicketTypeName,
    @UserName,
    @Status,
    @StatusPosition,
    @SeverityPosition,
    @IsClosed,
    @Severity,
    @TicketNumber,
    @IsVisibleOnPortal,
    @IsKnowledgeBase,
    @ReportedVersionID,
    @SolvedVersionID,
    @ProductID,
    @GroupID,
    @UserID,
    @TicketStatusID,
    @TicketTypeID,
    @TicketSeverityID,
    @OrganizationID,
    @Name,
    @ParentID,
    @ModifierID,
    @CreatorID,
    @DateModified,
    @DateCreated,
    @DateClosed,
    @CloserID,
    @DaysClosed,
    @MinutesClosed,
    @DaysOpened,
    @MinutesOpened,
    @CloserName,
    @CreatorName,
    @ModifierName,
    @HoursSpent,
    @Tags,
    @SlaViolationTime,
    @SlaWarningTime,
    @SlaViolationHours,
    @SlaWarningHours,
    @MinsSinceCreated,
    @DaysSinceCreated,
    @MinsSinceModified,
    @DaysSinceModified,
    @Contacts,
    @Customers,
    @SlaViolationTimeClosed,
    @SlaViolationLastAction,
    @SlaViolationInitialResponse,
    @SlaWarningTimeClosed,
    @SlaWarningLastAction,
    @SlaWarningInitialResponse,
    @NeedsIndexing,
    @SlaViolationDate,
    @SlaWarningDate,
    @TicketSource,
    @ForumCategory,
    @CategoryName,
    @CreatorEmail,
    @ModifierEmail,
    @KnowledgeBaseCategoryID,
    @KnowledgeBaseCategoryName,
    @KnowledgeBaseParentCategoryName,
    @DueDate,
    @SalesForceID,
    @DateModifiedBySalesForceSync,
    @DateModifiedByJiraSync,
    @JiraID,
    @SyncWithJira,
    @JiraKey,
    @JiraLinkURL,
    @JiraStatus,
    @ChildTicketCount,
    @RelatedTicketCount,
    @MinutesToInitialResponse,
    @DayOfWeekCreated,
    @HourOfDayCreated)

SET @Identity = SCOPE_IDENTITY()
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedUpdateReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedUpdateReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedUpdateReportTicketsViewItem

(
  @TicketID int,
  @ProductName varchar(255),
  @ReportedVersion varchar(50),
  @SolvedVersion varchar(50),
  @GroupName varchar(255),
  @TicketTypeName varchar(255),
  @UserName varchar(201),
  @Status varchar(255),
  @StatusPosition int,
  @SeverityPosition int,
  @IsClosed bit,
  @Severity varchar(255),
  @TicketNumber int,
  @IsVisibleOnPortal bit,
  @IsKnowledgeBase bit,
  @ReportedVersionID int,
  @SolvedVersionID int,
  @ProductID int,
  @GroupID int,
  @UserID int,
  @TicketStatusID int,
  @TicketTypeID int,
  @TicketSeverityID int,
  @OrganizationID int,
  @Name varchar(255),
  @ParentID int,
  @ModifierID int,
  @DateModified datetime,
  @DateClosed datetime,
  @CloserID int,
  @DaysClosed int,
  @MinutesClosed int,
  @DaysOpened int,
  @MinutesOpened int,
  @CloserName varchar(201),
  @CreatorName varchar(201),
  @ModifierName varchar(201),
  @HoursSpent decimal,
  @Tags varchar(8000),
  @SlaViolationTime int,
  @SlaWarningTime int,
  @SlaViolationHours decimal,
  @SlaWarningHours decimal,
  @MinsSinceCreated int,
  @DaysSinceCreated int,
  @MinsSinceModified int,
  @DaysSinceModified int,
  @Contacts varchar(8000),
  @Customers varchar(8000),
  @SlaViolationTimeClosed datetime,
  @SlaViolationLastAction datetime,
  @SlaViolationInitialResponse datetime,
  @SlaWarningTimeClosed datetime,
  @SlaWarningLastAction datetime,
  @SlaWarningInitialResponse datetime,
  @NeedsIndexing bit,
  @SlaViolationDate datetime,
  @SlaWarningDate datetime,
  @TicketSource varchar(50),
  @ForumCategory int,
  @CategoryName nvarchar(100),
  @CreatorEmail varchar(1024),
  @ModifierEmail varchar(1024),
  @KnowledgeBaseCategoryID int,
  @KnowledgeBaseCategoryName nvarchar(100),
  @KnowledgeBaseParentCategoryName nvarchar(100),
  @DueDate datetime,
  @SalesForceID varchar(8000),
  @DateModifiedBySalesForceSync datetime,
  @DateModifiedByJiraSync datetime,
  @JiraID int,
  @SyncWithJira bit,
  @JiraKey varchar(8000),
  @JiraLinkURL varchar(8000),
  @JiraStatus varchar(8000),
  @ChildTicketCount int,
  @RelatedTicketCount int,
  @MinutesToInitialResponse int,
  @DayOfWeekCreated nvarchar(30),
  @HourOfDayCreated int
)
AS
  SET NOCOUNT OFF;
  UPDATE [dbo].[ReportTicketsView]
  SET
    [ProductName] = @ProductName,
    [ReportedVersion] = @ReportedVersion,
    [SolvedVersion] = @SolvedVersion,
    [GroupName] = @GroupName,
    [TicketTypeName] = @TicketTypeName,
    [UserName] = @UserName,
    [Status] = @Status,
    [StatusPosition] = @StatusPosition,
    [SeverityPosition] = @SeverityPosition,
    [IsClosed] = @IsClosed,
    [Severity] = @Severity,
    [TicketNumber] = @TicketNumber,
    [IsVisibleOnPortal] = @IsVisibleOnPortal,
    [IsKnowledgeBase] = @IsKnowledgeBase,
    [ReportedVersionID] = @ReportedVersionID,
    [SolvedVersionID] = @SolvedVersionID,
    [ProductID] = @ProductID,
    [GroupID] = @GroupID,
    [UserID] = @UserID,
    [TicketStatusID] = @TicketStatusID,
    [TicketTypeID] = @TicketTypeID,
    [TicketSeverityID] = @TicketSeverityID,
    [OrganizationID] = @OrganizationID,
    [Name] = @Name,
    [ParentID] = @ParentID,
    [ModifierID] = @ModifierID,
    [DateModified] = @DateModified,
    [DateClosed] = @DateClosed,
    [CloserID] = @CloserID,
    [DaysClosed] = @DaysClosed,
    [MinutesClosed] = @MinutesClosed,
    [DaysOpened] = @DaysOpened,
    [MinutesOpened] = @MinutesOpened,
    [CloserName] = @CloserName,
    [CreatorName] = @CreatorName,
    [ModifierName] = @ModifierName,
    [HoursSpent] = @HoursSpent,
    [Tags] = @Tags,
    [SlaViolationTime] = @SlaViolationTime,
    [SlaWarningTime] = @SlaWarningTime,
    [SlaViolationHours] = @SlaViolationHours,
    [SlaWarningHours] = @SlaWarningHours,
    [MinsSinceCreated] = @MinsSinceCreated,
    [DaysSinceCreated] = @DaysSinceCreated,
    [MinsSinceModified] = @MinsSinceModified,
    [DaysSinceModified] = @DaysSinceModified,
    [Contacts] = @Contacts,
    [Customers] = @Customers,
    [SlaViolationTimeClosed] = @SlaViolationTimeClosed,
    [SlaViolationLastAction] = @SlaViolationLastAction,
    [SlaViolationInitialResponse] = @SlaViolationInitialResponse,
    [SlaWarningTimeClosed] = @SlaWarningTimeClosed,
    [SlaWarningLastAction] = @SlaWarningLastAction,
    [SlaWarningInitialResponse] = @SlaWarningInitialResponse,
    [NeedsIndexing] = @NeedsIndexing,
    [SlaViolationDate] = @SlaViolationDate,
    [SlaWarningDate] = @SlaWarningDate,
    [TicketSource] = @TicketSource,
    [ForumCategory] = @ForumCategory,
    [CategoryName] = @CategoryName,
    [CreatorEmail] = @CreatorEmail,
    [ModifierEmail] = @ModifierEmail,
    [KnowledgeBaseCategoryID] = @KnowledgeBaseCategoryID,
    [KnowledgeBaseCategoryName] = @KnowledgeBaseCategoryName,
    [KnowledgeBaseParentCategoryName] = @KnowledgeBaseParentCategoryName,
    [DueDate] = @DueDate,
    [SalesForceID] = @SalesForceID,
    [DateModifiedBySalesForceSync] = @DateModifiedBySalesForceSync,
    [DateModifiedByJiraSync] = @DateModifiedByJiraSync,
    [JiraID] = @JiraID,
    [SyncWithJira] = @SyncWithJira,
    [JiraKey] = @JiraKey,
    [JiraLinkURL] = @JiraLinkURL,
    [JiraStatus] = @JiraStatus,
    [ChildTicketCount] = @ChildTicketCount,
    [RelatedTicketCount] = @RelatedTicketCount,
    [MinutesToInitialResponse] = @MinutesToInitialResponse,
    [DayOfWeekCreated] = @DayOfWeekCreated,
    [HourOfDayCreated] = @HourOfDayCreated
  WHERE ([TicketID] = @TicketID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedDeleteReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedDeleteReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedDeleteReportTicketsViewItem

(
  @TicketID int
)
AS
  SET NOCOUNT OFF;
  DELETE FROM [dbo].[ReportTicketsView]
  WHERE ([TicketID] = @TicketID)
GO


IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedSelectReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedSelectReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedSelectReportTicketsViewItem

(
  @TicketID int
)
AS
  SET NOCOUNT OFF;
  SELECT
    [TicketID],
    [ProductName],
    [ReportedVersion],
    [SolvedVersion],
    [GroupName],
    [TicketTypeName],
    [UserName],
    [Status],
    [StatusPosition],
    [SeverityPosition],
    [IsClosed],
    [Severity],
    [TicketNumber],
    [IsVisibleOnPortal],
    [IsKnowledgeBase],
    [ReportedVersionID],
    [SolvedVersionID],
    [ProductID],
    [GroupID],
    [UserID],
    [TicketStatusID],
    [TicketTypeID],
    [TicketSeverityID],
    [OrganizationID],
    [Name],
    [ParentID],
    [ModifierID],
    [CreatorID],
    [DateModified],
    [DateCreated],
    [DateClosed],
    [CloserID],
    [DaysClosed],
    [MinutesClosed],
    [DaysOpened],
    [MinutesOpened],
    [CloserName],
    [CreatorName],
    [ModifierName],
    [HoursSpent],
    [Tags],
    [SlaViolationTime],
    [SlaWarningTime],
    [SlaViolationHours],
    [SlaWarningHours],
    [MinsSinceCreated],
    [DaysSinceCreated],
    [MinsSinceModified],
    [DaysSinceModified],
    [Contacts],
    [Customers],
    [SlaViolationTimeClosed],
    [SlaViolationLastAction],
    [SlaViolationInitialResponse],
    [SlaWarningTimeClosed],
    [SlaWarningLastAction],
    [SlaWarningInitialResponse],
    [NeedsIndexing],
    [SlaViolationDate],
    [SlaWarningDate],
    [TicketSource],
    [ForumCategory],
    [CategoryName],
    [CreatorEmail],
    [ModifierEmail],
    [KnowledgeBaseCategoryID],
    [KnowledgeBaseCategoryName],
    [KnowledgeBaseParentCategoryName],
    [DueDate],
    [SalesForceID],
    [DateModifiedBySalesForceSync],
    [DateModifiedByJiraSync],
    [JiraID],
    [SyncWithJira],
    [JiraKey],
    [JiraLinkURL],
    [JiraStatus],
    [ChildTicketCount],
    [RelatedTicketCount],
    [MinutesToInitialResponse],
    [DayOfWeekCreated],
    [HourOfDayCreated]
  FROM [dbo].[ReportTicketsView]
  WHERE ([TicketID] = @TicketID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedInsertReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedInsertReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedInsertReportTicketsViewItem

(
  @TicketID int,
  @ProductName varchar(255),
  @ReportedVersion varchar(50),
  @SolvedVersion varchar(50),
  @GroupName varchar(255),
  @TicketTypeName varchar(255),
  @UserName varchar(201),
  @Status varchar(255),
  @StatusPosition int,
  @SeverityPosition int,
  @IsClosed bit,
  @Severity varchar(255),
  @TicketNumber int,
  @IsVisibleOnPortal bit,
  @IsKnowledgeBase bit,
  @ReportedVersionID int,
  @SolvedVersionID int,
  @ProductID int,
  @GroupID int,
  @UserID int,
  @TicketStatusID int,
  @TicketTypeID int,
  @TicketSeverityID int,
  @OrganizationID int,
  @Name varchar(255),
  @ParentID int,
  @ModifierID int,
  @CreatorID int,
  @DateModified datetime,
  @DateCreated datetime,
  @DateClosed datetime,
  @CloserID int,
  @DaysClosed int,
  @MinutesClosed int,
  @DaysOpened int,
  @MinutesOpened int,
  @CloserName varchar(201),
  @CreatorName varchar(201),
  @ModifierName varchar(201),
  @HoursSpent decimal,
  @Tags varchar(8000),
  @SlaViolationTime int,
  @SlaWarningTime int,
  @SlaViolationHours decimal,
  @SlaWarningHours decimal,
  @MinsSinceCreated int,
  @DaysSinceCreated int,
  @MinsSinceModified int,
  @DaysSinceModified int,
  @Contacts varchar(8000),
  @Customers varchar(8000),
  @SlaViolationTimeClosed datetime,
  @SlaViolationLastAction datetime,
  @SlaViolationInitialResponse datetime,
  @SlaWarningTimeClosed datetime,
  @SlaWarningLastAction datetime,
  @SlaWarningInitialResponse datetime,
  @NeedsIndexing bit,
  @SlaViolationDate datetime,
  @SlaWarningDate datetime,
  @TicketSource varchar(50),
  @ForumCategory int,
  @CategoryName nvarchar(100),
  @CreatorEmail varchar(1024),
  @ModifierEmail varchar(1024),
  @KnowledgeBaseCategoryID int,
  @KnowledgeBaseCategoryName nvarchar(100),
  @KnowledgeBaseParentCategoryName nvarchar(100),
  @DueDate datetime,
  @SalesForceID varchar(8000),
  @DateModifiedBySalesForceSync datetime,
  @DateModifiedByJiraSync datetime,
  @JiraID int,
  @SyncWithJira bit,
  @JiraKey varchar(8000),
  @JiraLinkURL varchar(8000),
  @JiraStatus varchar(8000),
  @ChildTicketCount int,
  @RelatedTicketCount int,
  @MinutesToInitialResponse int,
  @DayOfWeekCreated nvarchar(30),
  @HourOfDayCreated int,
  @Identity int OUT
)
AS
  SET NOCOUNT OFF;
  INSERT INTO [dbo].[ReportTicketsView]
  (
    [TicketID],
    [ProductName],
    [ReportedVersion],
    [SolvedVersion],
    [GroupName],
    [TicketTypeName],
    [UserName],
    [Status],
    [StatusPosition],
    [SeverityPosition],
    [IsClosed],
    [Severity],
    [TicketNumber],
    [IsVisibleOnPortal],
    [IsKnowledgeBase],
    [ReportedVersionID],
    [SolvedVersionID],
    [ProductID],
    [GroupID],
    [UserID],
    [TicketStatusID],
    [TicketTypeID],
    [TicketSeverityID],
    [OrganizationID],
    [Name],
    [ParentID],
    [ModifierID],
    [CreatorID],
    [DateModified],
    [DateCreated],
    [DateClosed],
    [CloserID],
    [DaysClosed],
    [MinutesClosed],
    [DaysOpened],
    [MinutesOpened],
    [CloserName],
    [CreatorName],
    [ModifierName],
    [HoursSpent],
    [Tags],
    [SlaViolationTime],
    [SlaWarningTime],
    [SlaViolationHours],
    [SlaWarningHours],
    [MinsSinceCreated],
    [DaysSinceCreated],
    [MinsSinceModified],
    [DaysSinceModified],
    [Contacts],
    [Customers],
    [SlaViolationTimeClosed],
    [SlaViolationLastAction],
    [SlaViolationInitialResponse],
    [SlaWarningTimeClosed],
    [SlaWarningLastAction],
    [SlaWarningInitialResponse],
    [NeedsIndexing],
    [SlaViolationDate],
    [SlaWarningDate],
    [TicketSource],
    [ForumCategory],
    [CategoryName],
    [CreatorEmail],
    [ModifierEmail],
    [KnowledgeBaseCategoryID],
    [KnowledgeBaseCategoryName],
    [KnowledgeBaseParentCategoryName],
    [DueDate],
    [SalesForceID],
    [DateModifiedBySalesForceSync],
    [DateModifiedByJiraSync],
    [JiraID],
    [SyncWithJira],
    [JiraKey],
    [JiraLinkURL],
    [JiraStatus],
    [ChildTicketCount],
    [RelatedTicketCount],
    [MinutesToInitialResponse],
    [DayOfWeekCreated],
    [HourOfDayCreated])
  VALUES (
    @TicketID,
    @ProductName,
    @ReportedVersion,
    @SolvedVersion,
    @GroupName,
    @TicketTypeName,
    @UserName,
    @Status,
    @StatusPosition,
    @SeverityPosition,
    @IsClosed,
    @Severity,
    @TicketNumber,
    @IsVisibleOnPortal,
    @IsKnowledgeBase,
    @ReportedVersionID,
    @SolvedVersionID,
    @ProductID,
    @GroupID,
    @UserID,
    @TicketStatusID,
    @TicketTypeID,
    @TicketSeverityID,
    @OrganizationID,
    @Name,
    @ParentID,
    @ModifierID,
    @CreatorID,
    @DateModified,
    @DateCreated,
    @DateClosed,
    @CloserID,
    @DaysClosed,
    @MinutesClosed,
    @DaysOpened,
    @MinutesOpened,
    @CloserName,
    @CreatorName,
    @ModifierName,
    @HoursSpent,
    @Tags,
    @SlaViolationTime,
    @SlaWarningTime,
    @SlaViolationHours,
    @SlaWarningHours,
    @MinsSinceCreated,
    @DaysSinceCreated,
    @MinsSinceModified,
    @DaysSinceModified,
    @Contacts,
    @Customers,
    @SlaViolationTimeClosed,
    @SlaViolationLastAction,
    @SlaViolationInitialResponse,
    @SlaWarningTimeClosed,
    @SlaWarningLastAction,
    @SlaWarningInitialResponse,
    @NeedsIndexing,
    @SlaViolationDate,
    @SlaWarningDate,
    @TicketSource,
    @ForumCategory,
    @CategoryName,
    @CreatorEmail,
    @ModifierEmail,
    @KnowledgeBaseCategoryID,
    @KnowledgeBaseCategoryName,
    @KnowledgeBaseParentCategoryName,
    @DueDate,
    @SalesForceID,
    @DateModifiedBySalesForceSync,
    @DateModifiedByJiraSync,
    @JiraID,
    @SyncWithJira,
    @JiraKey,
    @JiraLinkURL,
    @JiraStatus,
    @ChildTicketCount,
    @RelatedTicketCount,
    @MinutesToInitialResponse,
    @DayOfWeekCreated,
    @HourOfDayCreated)

SET @Identity = SCOPE_IDENTITY()
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedUpdateReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedUpdateReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedUpdateReportTicketsViewItem

(
  @TicketID int,
  @ProductName varchar(255),
  @ReportedVersion varchar(50),
  @SolvedVersion varchar(50),
  @GroupName varchar(255),
  @TicketTypeName varchar(255),
  @UserName varchar(201),
  @Status varchar(255),
  @StatusPosition int,
  @SeverityPosition int,
  @IsClosed bit,
  @Severity varchar(255),
  @TicketNumber int,
  @IsVisibleOnPortal bit,
  @IsKnowledgeBase bit,
  @ReportedVersionID int,
  @SolvedVersionID int,
  @ProductID int,
  @GroupID int,
  @UserID int,
  @TicketStatusID int,
  @TicketTypeID int,
  @TicketSeverityID int,
  @OrganizationID int,
  @Name varchar(255),
  @ParentID int,
  @ModifierID int,
  @DateModified datetime,
  @DateClosed datetime,
  @CloserID int,
  @DaysClosed int,
  @MinutesClosed int,
  @DaysOpened int,
  @MinutesOpened int,
  @CloserName varchar(201),
  @CreatorName varchar(201),
  @ModifierName varchar(201),
  @HoursSpent decimal,
  @Tags varchar(8000),
  @SlaViolationTime int,
  @SlaWarningTime int,
  @SlaViolationHours decimal,
  @SlaWarningHours decimal,
  @MinsSinceCreated int,
  @DaysSinceCreated int,
  @MinsSinceModified int,
  @DaysSinceModified int,
  @Contacts varchar(8000),
  @Customers varchar(8000),
  @SlaViolationTimeClosed datetime,
  @SlaViolationLastAction datetime,
  @SlaViolationInitialResponse datetime,
  @SlaWarningTimeClosed datetime,
  @SlaWarningLastAction datetime,
  @SlaWarningInitialResponse datetime,
  @NeedsIndexing bit,
  @SlaViolationDate datetime,
  @SlaWarningDate datetime,
  @TicketSource varchar(50),
  @ForumCategory int,
  @CategoryName nvarchar(100),
  @CreatorEmail varchar(1024),
  @ModifierEmail varchar(1024),
  @KnowledgeBaseCategoryID int,
  @KnowledgeBaseCategoryName nvarchar(100),
  @KnowledgeBaseParentCategoryName nvarchar(100),
  @DueDate datetime,
  @SalesForceID varchar(8000),
  @DateModifiedBySalesForceSync datetime,
  @DateModifiedByJiraSync datetime,
  @JiraID int,
  @SyncWithJira bit,
  @JiraKey varchar(8000),
  @JiraLinkURL varchar(8000),
  @JiraStatus varchar(8000),
  @ChildTicketCount int,
  @RelatedTicketCount int,
  @MinutesToInitialResponse int,
  @DayOfWeekCreated nvarchar(30),
  @HourOfDayCreated int
)
AS
  SET NOCOUNT OFF;
  UPDATE [dbo].[ReportTicketsView]
  SET
    [ProductName] = @ProductName,
    [ReportedVersion] = @ReportedVersion,
    [SolvedVersion] = @SolvedVersion,
    [GroupName] = @GroupName,
    [TicketTypeName] = @TicketTypeName,
    [UserName] = @UserName,
    [Status] = @Status,
    [StatusPosition] = @StatusPosition,
    [SeverityPosition] = @SeverityPosition,
    [IsClosed] = @IsClosed,
    [Severity] = @Severity,
    [TicketNumber] = @TicketNumber,
    [IsVisibleOnPortal] = @IsVisibleOnPortal,
    [IsKnowledgeBase] = @IsKnowledgeBase,
    [ReportedVersionID] = @ReportedVersionID,
    [SolvedVersionID] = @SolvedVersionID,
    [ProductID] = @ProductID,
    [GroupID] = @GroupID,
    [UserID] = @UserID,
    [TicketStatusID] = @TicketStatusID,
    [TicketTypeID] = @TicketTypeID,
    [TicketSeverityID] = @TicketSeverityID,
    [OrganizationID] = @OrganizationID,
    [Name] = @Name,
    [ParentID] = @ParentID,
    [ModifierID] = @ModifierID,
    [DateModified] = @DateModified,
    [DateClosed] = @DateClosed,
    [CloserID] = @CloserID,
    [DaysClosed] = @DaysClosed,
    [MinutesClosed] = @MinutesClosed,
    [DaysOpened] = @DaysOpened,
    [MinutesOpened] = @MinutesOpened,
    [CloserName] = @CloserName,
    [CreatorName] = @CreatorName,
    [ModifierName] = @ModifierName,
    [HoursSpent] = @HoursSpent,
    [Tags] = @Tags,
    [SlaViolationTime] = @SlaViolationTime,
    [SlaWarningTime] = @SlaWarningTime,
    [SlaViolationHours] = @SlaViolationHours,
    [SlaWarningHours] = @SlaWarningHours,
    [MinsSinceCreated] = @MinsSinceCreated,
    [DaysSinceCreated] = @DaysSinceCreated,
    [MinsSinceModified] = @MinsSinceModified,
    [DaysSinceModified] = @DaysSinceModified,
    [Contacts] = @Contacts,
    [Customers] = @Customers,
    [SlaViolationTimeClosed] = @SlaViolationTimeClosed,
    [SlaViolationLastAction] = @SlaViolationLastAction,
    [SlaViolationInitialResponse] = @SlaViolationInitialResponse,
    [SlaWarningTimeClosed] = @SlaWarningTimeClosed,
    [SlaWarningLastAction] = @SlaWarningLastAction,
    [SlaWarningInitialResponse] = @SlaWarningInitialResponse,
    [NeedsIndexing] = @NeedsIndexing,
    [SlaViolationDate] = @SlaViolationDate,
    [SlaWarningDate] = @SlaWarningDate,
    [TicketSource] = @TicketSource,
    [ForumCategory] = @ForumCategory,
    [CategoryName] = @CategoryName,
    [CreatorEmail] = @CreatorEmail,
    [ModifierEmail] = @ModifierEmail,
    [KnowledgeBaseCategoryID] = @KnowledgeBaseCategoryID,
    [KnowledgeBaseCategoryName] = @KnowledgeBaseCategoryName,
    [KnowledgeBaseParentCategoryName] = @KnowledgeBaseParentCategoryName,
    [DueDate] = @DueDate,
    [SalesForceID] = @SalesForceID,
    [DateModifiedBySalesForceSync] = @DateModifiedBySalesForceSync,
    [DateModifiedByJiraSync] = @DateModifiedByJiraSync,
    [JiraID] = @JiraID,
    [SyncWithJira] = @SyncWithJira,
    [JiraKey] = @JiraKey,
    [JiraLinkURL] = @JiraLinkURL,
    [JiraStatus] = @JiraStatus,
    [ChildTicketCount] = @ChildTicketCount,
    [RelatedTicketCount] = @RelatedTicketCount,
    [MinutesToInitialResponse] = @MinutesToInitialResponse,
    [DayOfWeekCreated] = @DayOfWeekCreated,
    [HourOfDayCreated] = @HourOfDayCreated
  WHERE ([TicketID] = @TicketID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedDeleteReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedDeleteReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedDeleteReportTicketsViewItem

(
  @TicketID int
)
AS
  SET NOCOUNT OFF;
  DELETE FROM [dbo].[ReportTicketsView]
  WHERE ([TicketID] = @TicketID)
GO


IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedSelectReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedSelectReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedSelectReportTicketsViewItem

(
  @TicketID int
)
AS
  SET NOCOUNT OFF;
  SELECT
    [TicketID],
    [ProductName],
    [ReportedVersion],
    [SolvedVersion],
    [GroupName],
    [TicketTypeName],
    [UserName],
    [Status],
    [StatusPosition],
    [SeverityPosition],
    [IsClosed],
    [Severity],
    [TicketNumber],
    [IsVisibleOnPortal],
    [IsKnowledgeBase],
    [ReportedVersionID],
    [SolvedVersionID],
    [ProductID],
    [GroupID],
    [UserID],
    [TicketStatusID],
    [TicketTypeID],
    [TicketSeverityID],
    [OrganizationID],
    [Name],
    [ParentID],
    [ModifierID],
    [CreatorID],
    [DateModified],
    [DateCreated],
    [DateClosed],
    [CloserID],
    [DaysClosed],
    [MinutesClosed],
    [DaysOpened],
    [MinutesOpened],
    [CloserName],
    [CreatorName],
    [ModifierName],
    [HoursSpent],
    [Tags],
    [SlaViolationTime],
    [SlaWarningTime],
    [SlaViolationHours],
    [SlaWarningHours],
    [MinsSinceCreated],
    [DaysSinceCreated],
    [MinsSinceModified],
    [DaysSinceModified],
    [Contacts],
    [Customers],
    [SlaViolationTimeClosed],
    [SlaViolationLastAction],
    [SlaViolationInitialResponse],
    [SlaWarningTimeClosed],
    [SlaWarningLastAction],
    [SlaWarningInitialResponse],
    [NeedsIndexing],
    [SlaViolationDate],
    [SlaWarningDate],
    [TicketSource],
    [ForumCategory],
    [CategoryName],
    [CreatorEmail],
    [ModifierEmail],
    [KnowledgeBaseCategoryID],
    [KnowledgeBaseCategoryName],
    [KnowledgeBaseParentCategoryName],
    [DueDate],
    [SalesForceID],
    [DateModifiedBySalesForceSync],
    [DateModifiedByJiraSync],
    [JiraID],
    [SyncWithJira],
    [JiraKey],
    [JiraLinkURL],
    [JiraStatus],
    [ChildTicketCount],
    [RelatedTicketCount],
    [MinutesToInitialResponse],
    [DayOfWeekCreated],
    [HourOfDayCreated]
  FROM [dbo].[ReportTicketsView]
  WHERE ([TicketID] = @TicketID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedInsertReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedInsertReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedInsertReportTicketsViewItem

(
  @TicketID int,
  @ProductName varchar(255),
  @ReportedVersion varchar(50),
  @SolvedVersion varchar(50),
  @GroupName varchar(255),
  @TicketTypeName varchar(255),
  @UserName varchar(201),
  @Status varchar(255),
  @StatusPosition int,
  @SeverityPosition int,
  @IsClosed bit,
  @Severity varchar(255),
  @TicketNumber int,
  @IsVisibleOnPortal bit,
  @IsKnowledgeBase bit,
  @ReportedVersionID int,
  @SolvedVersionID int,
  @ProductID int,
  @GroupID int,
  @UserID int,
  @TicketStatusID int,
  @TicketTypeID int,
  @TicketSeverityID int,
  @OrganizationID int,
  @Name varchar(255),
  @ParentID int,
  @ModifierID int,
  @CreatorID int,
  @DateModified datetime,
  @DateCreated datetime,
  @DateClosed datetime,
  @CloserID int,
  @DaysClosed int,
  @MinutesClosed int,
  @DaysOpened int,
  @MinutesOpened int,
  @CloserName varchar(201),
  @CreatorName varchar(201),
  @ModifierName varchar(201),
  @HoursSpent decimal,
  @Tags varchar(8000),
  @SlaViolationTime int,
  @SlaWarningTime int,
  @SlaViolationHours decimal,
  @SlaWarningHours decimal,
  @MinsSinceCreated int,
  @DaysSinceCreated int,
  @MinsSinceModified int,
  @DaysSinceModified int,
  @Contacts varchar(8000),
  @Customers varchar(8000),
  @SlaViolationTimeClosed datetime,
  @SlaViolationLastAction datetime,
  @SlaViolationInitialResponse datetime,
  @SlaWarningTimeClosed datetime,
  @SlaWarningLastAction datetime,
  @SlaWarningInitialResponse datetime,
  @NeedsIndexing bit,
  @SlaViolationDate datetime,
  @SlaWarningDate datetime,
  @TicketSource varchar(50),
  @ForumCategory int,
  @CategoryName nvarchar(100),
  @CreatorEmail varchar(1024),
  @ModifierEmail varchar(1024),
  @KnowledgeBaseCategoryID int,
  @KnowledgeBaseCategoryName nvarchar(100),
  @KnowledgeBaseParentCategoryName nvarchar(100),
  @DueDate datetime,
  @SalesForceID varchar(8000),
  @DateModifiedBySalesForceSync datetime,
  @DateModifiedByJiraSync datetime,
  @JiraID int,
  @SyncWithJira bit,
  @JiraKey varchar(8000),
  @JiraLinkURL varchar(8000),
  @JiraStatus varchar(8000),
  @ChildTicketCount int,
  @RelatedTicketCount int,
  @MinutesToInitialResponse int,
  @DayOfWeekCreated nvarchar(30),
  @HourOfDayCreated int,
  @Identity int OUT
)
AS
  SET NOCOUNT OFF;
  INSERT INTO [dbo].[ReportTicketsView]
  (
    [TicketID],
    [ProductName],
    [ReportedVersion],
    [SolvedVersion],
    [GroupName],
    [TicketTypeName],
    [UserName],
    [Status],
    [StatusPosition],
    [SeverityPosition],
    [IsClosed],
    [Severity],
    [TicketNumber],
    [IsVisibleOnPortal],
    [IsKnowledgeBase],
    [ReportedVersionID],
    [SolvedVersionID],
    [ProductID],
    [GroupID],
    [UserID],
    [TicketStatusID],
    [TicketTypeID],
    [TicketSeverityID],
    [OrganizationID],
    [Name],
    [ParentID],
    [ModifierID],
    [CreatorID],
    [DateModified],
    [DateCreated],
    [DateClosed],
    [CloserID],
    [DaysClosed],
    [MinutesClosed],
    [DaysOpened],
    [MinutesOpened],
    [CloserName],
    [CreatorName],
    [ModifierName],
    [HoursSpent],
    [Tags],
    [SlaViolationTime],
    [SlaWarningTime],
    [SlaViolationHours],
    [SlaWarningHours],
    [MinsSinceCreated],
    [DaysSinceCreated],
    [MinsSinceModified],
    [DaysSinceModified],
    [Contacts],
    [Customers],
    [SlaViolationTimeClosed],
    [SlaViolationLastAction],
    [SlaViolationInitialResponse],
    [SlaWarningTimeClosed],
    [SlaWarningLastAction],
    [SlaWarningInitialResponse],
    [NeedsIndexing],
    [SlaViolationDate],
    [SlaWarningDate],
    [TicketSource],
    [ForumCategory],
    [CategoryName],
    [CreatorEmail],
    [ModifierEmail],
    [KnowledgeBaseCategoryID],
    [KnowledgeBaseCategoryName],
    [KnowledgeBaseParentCategoryName],
    [DueDate],
    [SalesForceID],
    [DateModifiedBySalesForceSync],
    [DateModifiedByJiraSync],
    [JiraID],
    [SyncWithJira],
    [JiraKey],
    [JiraLinkURL],
    [JiraStatus],
    [ChildTicketCount],
    [RelatedTicketCount],
    [MinutesToInitialResponse],
    [DayOfWeekCreated],
    [HourOfDayCreated])
  VALUES (
    @TicketID,
    @ProductName,
    @ReportedVersion,
    @SolvedVersion,
    @GroupName,
    @TicketTypeName,
    @UserName,
    @Status,
    @StatusPosition,
    @SeverityPosition,
    @IsClosed,
    @Severity,
    @TicketNumber,
    @IsVisibleOnPortal,
    @IsKnowledgeBase,
    @ReportedVersionID,
    @SolvedVersionID,
    @ProductID,
    @GroupID,
    @UserID,
    @TicketStatusID,
    @TicketTypeID,
    @TicketSeverityID,
    @OrganizationID,
    @Name,
    @ParentID,
    @ModifierID,
    @CreatorID,
    @DateModified,
    @DateCreated,
    @DateClosed,
    @CloserID,
    @DaysClosed,
    @MinutesClosed,
    @DaysOpened,
    @MinutesOpened,
    @CloserName,
    @CreatorName,
    @ModifierName,
    @HoursSpent,
    @Tags,
    @SlaViolationTime,
    @SlaWarningTime,
    @SlaViolationHours,
    @SlaWarningHours,
    @MinsSinceCreated,
    @DaysSinceCreated,
    @MinsSinceModified,
    @DaysSinceModified,
    @Contacts,
    @Customers,
    @SlaViolationTimeClosed,
    @SlaViolationLastAction,
    @SlaViolationInitialResponse,
    @SlaWarningTimeClosed,
    @SlaWarningLastAction,
    @SlaWarningInitialResponse,
    @NeedsIndexing,
    @SlaViolationDate,
    @SlaWarningDate,
    @TicketSource,
    @ForumCategory,
    @CategoryName,
    @CreatorEmail,
    @ModifierEmail,
    @KnowledgeBaseCategoryID,
    @KnowledgeBaseCategoryName,
    @KnowledgeBaseParentCategoryName,
    @DueDate,
    @SalesForceID,
    @DateModifiedBySalesForceSync,
    @DateModifiedByJiraSync,
    @JiraID,
    @SyncWithJira,
    @JiraKey,
    @JiraLinkURL,
    @JiraStatus,
    @ChildTicketCount,
    @RelatedTicketCount,
    @MinutesToInitialResponse,
    @DayOfWeekCreated,
    @HourOfDayCreated)

SET @Identity = SCOPE_IDENTITY()
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedUpdateReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedUpdateReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedUpdateReportTicketsViewItem

(
  @TicketID int,
  @ProductName varchar(255),
  @ReportedVersion varchar(50),
  @SolvedVersion varchar(50),
  @GroupName varchar(255),
  @TicketTypeName varchar(255),
  @UserName varchar(201),
  @Status varchar(255),
  @StatusPosition int,
  @SeverityPosition int,
  @IsClosed bit,
  @Severity varchar(255),
  @TicketNumber int,
  @IsVisibleOnPortal bit,
  @IsKnowledgeBase bit,
  @ReportedVersionID int,
  @SolvedVersionID int,
  @ProductID int,
  @GroupID int,
  @UserID int,
  @TicketStatusID int,
  @TicketTypeID int,
  @TicketSeverityID int,
  @OrganizationID int,
  @Name varchar(255),
  @ParentID int,
  @ModifierID int,
  @DateModified datetime,
  @DateClosed datetime,
  @CloserID int,
  @DaysClosed int,
  @MinutesClosed int,
  @DaysOpened int,
  @MinutesOpened int,
  @CloserName varchar(201),
  @CreatorName varchar(201),
  @ModifierName varchar(201),
  @HoursSpent decimal,
  @Tags varchar(8000),
  @SlaViolationTime int,
  @SlaWarningTime int,
  @SlaViolationHours decimal,
  @SlaWarningHours decimal,
  @MinsSinceCreated int,
  @DaysSinceCreated int,
  @MinsSinceModified int,
  @DaysSinceModified int,
  @Contacts varchar(8000),
  @Customers varchar(8000),
  @SlaViolationTimeClosed datetime,
  @SlaViolationLastAction datetime,
  @SlaViolationInitialResponse datetime,
  @SlaWarningTimeClosed datetime,
  @SlaWarningLastAction datetime,
  @SlaWarningInitialResponse datetime,
  @NeedsIndexing bit,
  @SlaViolationDate datetime,
  @SlaWarningDate datetime,
  @TicketSource varchar(50),
  @ForumCategory int,
  @CategoryName nvarchar(100),
  @CreatorEmail varchar(1024),
  @ModifierEmail varchar(1024),
  @KnowledgeBaseCategoryID int,
  @KnowledgeBaseCategoryName nvarchar(100),
  @KnowledgeBaseParentCategoryName nvarchar(100),
  @DueDate datetime,
  @SalesForceID varchar(8000),
  @DateModifiedBySalesForceSync datetime,
  @DateModifiedByJiraSync datetime,
  @JiraID int,
  @SyncWithJira bit,
  @JiraKey varchar(8000),
  @JiraLinkURL varchar(8000),
  @JiraStatus varchar(8000),
  @ChildTicketCount int,
  @RelatedTicketCount int,
  @MinutesToInitialResponse int,
  @DayOfWeekCreated nvarchar(30),
  @HourOfDayCreated int
)
AS
  SET NOCOUNT OFF;
  UPDATE [dbo].[ReportTicketsView]
  SET
    [ProductName] = @ProductName,
    [ReportedVersion] = @ReportedVersion,
    [SolvedVersion] = @SolvedVersion,
    [GroupName] = @GroupName,
    [TicketTypeName] = @TicketTypeName,
    [UserName] = @UserName,
    [Status] = @Status,
    [StatusPosition] = @StatusPosition,
    [SeverityPosition] = @SeverityPosition,
    [IsClosed] = @IsClosed,
    [Severity] = @Severity,
    [TicketNumber] = @TicketNumber,
    [IsVisibleOnPortal] = @IsVisibleOnPortal,
    [IsKnowledgeBase] = @IsKnowledgeBase,
    [ReportedVersionID] = @ReportedVersionID,
    [SolvedVersionID] = @SolvedVersionID,
    [ProductID] = @ProductID,
    [GroupID] = @GroupID,
    [UserID] = @UserID,
    [TicketStatusID] = @TicketStatusID,
    [TicketTypeID] = @TicketTypeID,
    [TicketSeverityID] = @TicketSeverityID,
    [OrganizationID] = @OrganizationID,
    [Name] = @Name,
    [ParentID] = @ParentID,
    [ModifierID] = @ModifierID,
    [DateModified] = @DateModified,
    [DateClosed] = @DateClosed,
    [CloserID] = @CloserID,
    [DaysClosed] = @DaysClosed,
    [MinutesClosed] = @MinutesClosed,
    [DaysOpened] = @DaysOpened,
    [MinutesOpened] = @MinutesOpened,
    [CloserName] = @CloserName,
    [CreatorName] = @CreatorName,
    [ModifierName] = @ModifierName,
    [HoursSpent] = @HoursSpent,
    [Tags] = @Tags,
    [SlaViolationTime] = @SlaViolationTime,
    [SlaWarningTime] = @SlaWarningTime,
    [SlaViolationHours] = @SlaViolationHours,
    [SlaWarningHours] = @SlaWarningHours,
    [MinsSinceCreated] = @MinsSinceCreated,
    [DaysSinceCreated] = @DaysSinceCreated,
    [MinsSinceModified] = @MinsSinceModified,
    [DaysSinceModified] = @DaysSinceModified,
    [Contacts] = @Contacts,
    [Customers] = @Customers,
    [SlaViolationTimeClosed] = @SlaViolationTimeClosed,
    [SlaViolationLastAction] = @SlaViolationLastAction,
    [SlaViolationInitialResponse] = @SlaViolationInitialResponse,
    [SlaWarningTimeClosed] = @SlaWarningTimeClosed,
    [SlaWarningLastAction] = @SlaWarningLastAction,
    [SlaWarningInitialResponse] = @SlaWarningInitialResponse,
    [NeedsIndexing] = @NeedsIndexing,
    [SlaViolationDate] = @SlaViolationDate,
    [SlaWarningDate] = @SlaWarningDate,
    [TicketSource] = @TicketSource,
    [ForumCategory] = @ForumCategory,
    [CategoryName] = @CategoryName,
    [CreatorEmail] = @CreatorEmail,
    [ModifierEmail] = @ModifierEmail,
    [KnowledgeBaseCategoryID] = @KnowledgeBaseCategoryID,
    [KnowledgeBaseCategoryName] = @KnowledgeBaseCategoryName,
    [KnowledgeBaseParentCategoryName] = @KnowledgeBaseParentCategoryName,
    [DueDate] = @DueDate,
    [SalesForceID] = @SalesForceID,
    [DateModifiedBySalesForceSync] = @DateModifiedBySalesForceSync,
    [DateModifiedByJiraSync] = @DateModifiedByJiraSync,
    [JiraID] = @JiraID,
    [SyncWithJira] = @SyncWithJira,
    [JiraKey] = @JiraKey,
    [JiraLinkURL] = @JiraLinkURL,
    [JiraStatus] = @JiraStatus,
    [ChildTicketCount] = @ChildTicketCount,
    [RelatedTicketCount] = @RelatedTicketCount,
    [MinutesToInitialResponse] = @MinutesToInitialResponse,
    [DayOfWeekCreated] = @DayOfWeekCreated,
    [HourOfDayCreated] = @HourOfDayCreated
  WHERE ([TicketID] = @TicketID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedDeleteReportTicketsViewItem' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedDeleteReportTicketsViewItem
GO

CREATE PROCEDURE dbo.uspGeneratedDeleteReportTicketsViewItem

(
  @TicketID int
)
AS
  SET NOCOUNT OFF;
  DELETE FROM [dbo].[ReportTicketsView]
  WHERE ([TicketID] = @TicketID)
GO


