IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedSelectUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedSelectUser
GO

CREATE PROCEDURE dbo.uspGeneratedSelectUser

(
  @UserID int
)
AS
  SET NOCOUNT OFF;
  SELECT
    [UserID],
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [Title],
    [CryptedPassword],
    [IsActive],
    [MarkDeleted],
    [TimeZoneID],
    [CultureName],
    [LastLogin],
    [LastActivity],
    [LastPing],
    [LastWaterCoolerID],
    [IsSystemAdmin],
    [IsFinanceAdmin],
    [IsPasswordExpired],
    [IsPortalUser],
    [IsChatUser],
    [PrimaryGroupID],
    [InOffice],
    [InOfficeComment],
    [ReceiveTicketNotifications],
    [ReceiveAllGroupNotifications],
    [SubscribeToNewTickets],
    [ActivatedOn],
    [DeactivatedOn],
    [OrganizationID],
    [LastVersion],
    [SessionID],
    [ImportID],
    [DateCreated],
    [DateModified],
    [CreatorID],
    [ModifierID],
    [OrgsUserCanSeeOnPortal],
    [DoNotAutoSubscribe],
    [IsClassicView],
    [SubscribeToNewActions],
    [ApprovedTerms],
    [ShowWelcomePage],
    [UserInformation],
    [PortalAutoReg],
    [AppChatID],
    [AppChatStatus],
    [MenuItems],
    [TicketRights],
    [Signature],
    [LinkedIn],
    [OnlyEmailAfterHours],
    [BlockInboundEmail],
    [SalesForceID],
    [ChangeTicketVisibility],
    [ChangeKBVisibility],
    [EnforceSingleSession],
    [NeedsIndexing],
    [AllowAnyTicketCustomer],
    [FontFamily],
    [FontSize],
    [CanCreateCompany],
    [CanEditCompany],
    [CanCreateContact],
    [CanEditContact],
    [RestrictUserFromEditingAnyActions],
    [AllowUserToEditAnyAction],
    [UserCanPinAction],
    [PortalLimitOrgTickets],
    [CanCreateAsset],
    [CanEditAsset],
    [CanChangeCommunityVisibility],
    [FilterInactive],
    [DisableExporting],
    [CanCreateProducts],
    [CanEditProducts],
    [CanCreateVersions],
    [CanEditVersions],
    [ReceiveUnassignedGroupEmails],
    [ProductFamiliesRights],
    [BlockEmailFromCreatingOnly]
  FROM [dbo].[Users]
  WHERE ([UserID] = @UserID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedInsertUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedInsertUser
GO

CREATE PROCEDURE dbo.uspGeneratedInsertUser

(
  @Email varchar(1024),
  @FirstName varchar(100),
  @MiddleName varchar(100),
  @LastName varchar(100),
  @Title varchar(100),
  @CryptedPassword varchar(255),
  @IsActive bit,
  @MarkDeleted bit,
  @TimeZoneID varchar(300),
  @CultureName varchar(50),
  @LastLogin datetime,
  @LastActivity datetime,
  @LastPing datetime,
  @LastWaterCoolerID int,
  @IsSystemAdmin bit,
  @IsFinanceAdmin bit,
  @IsPasswordExpired bit,
  @IsPortalUser bit,
  @IsChatUser bit,
  @PrimaryGroupID int,
  @InOffice bit,
  @InOfficeComment varchar(200),
  @ReceiveTicketNotifications bit,
  @ReceiveAllGroupNotifications bit,
  @SubscribeToNewTickets bit,
  @ActivatedOn datetime,
  @DeactivatedOn datetime,
  @OrganizationID int,
  @LastVersion varchar(50),
  @SessionID uniqueidentifier,
  @ImportID varchar(500),
  @DateCreated datetime,
  @DateModified datetime,
  @CreatorID int,
  @ModifierID int,
  @OrgsUserCanSeeOnPortal varchar(200),
  @DoNotAutoSubscribe bit,
  @IsClassicView bit,
  @SubscribeToNewActions bit,
  @ApprovedTerms bit,
  @ShowWelcomePage bit,
  @UserInformation varchar(MAX),
  @PortalAutoReg bit,
  @AppChatID varchar(200),
  @AppChatStatus bit,
  @MenuItems varchar(1000),
  @TicketRights int,
  @Signature varchar(MAX),
  @LinkedIn varchar(200),
  @OnlyEmailAfterHours bit,
  @BlockInboundEmail bit,
  @SalesForceID varchar(8000),
  @ChangeTicketVisibility bit,
  @ChangeKBVisibility bit,
  @EnforceSingleSession bit,
  @NeedsIndexing bit,
  @AllowAnyTicketCustomer bit,
  @FontFamily int,
  @FontSize int,
  @CanCreateCompany bit,
  @CanEditCompany bit,
  @CanCreateContact bit,
  @CanEditContact bit,
  @RestrictUserFromEditingAnyActions bit,
  @AllowUserToEditAnyAction bit,
  @UserCanPinAction bit,
  @PortalLimitOrgTickets bit,
  @CanCreateAsset bit,
  @CanEditAsset bit,
  @CanChangeCommunityVisibility bit,
  @FilterInactive bit,
  @DisableExporting bit,
  @CanCreateProducts bit,
  @CanEditProducts bit,
  @CanCreateVersions bit,
  @CanEditVersions bit,
  @ReceiveUnassignedGroupEmails bit,
  @ProductFamiliesRights int,
  @BlockEmailFromCreatingOnly bit,
  @Identity int OUT
)
AS
  SET NOCOUNT OFF;
  INSERT INTO [dbo].[Users]
  (
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [Title],
    [CryptedPassword],
    [IsActive],
    [MarkDeleted],
    [TimeZoneID],
    [CultureName],
    [LastLogin],
    [LastActivity],
    [LastPing],
    [LastWaterCoolerID],
    [IsSystemAdmin],
    [IsFinanceAdmin],
    [IsPasswordExpired],
    [IsPortalUser],
    [IsChatUser],
    [PrimaryGroupID],
    [InOffice],
    [InOfficeComment],
    [ReceiveTicketNotifications],
    [ReceiveAllGroupNotifications],
    [SubscribeToNewTickets],
    [ActivatedOn],
    [DeactivatedOn],
    [OrganizationID],
    [LastVersion],
    [SessionID],
    [ImportID],
    [DateCreated],
    [DateModified],
    [CreatorID],
    [ModifierID],
    [OrgsUserCanSeeOnPortal],
    [DoNotAutoSubscribe],
    [IsClassicView],
    [SubscribeToNewActions],
    [ApprovedTerms],
    [ShowWelcomePage],
    [UserInformation],
    [PortalAutoReg],
    [AppChatID],
    [AppChatStatus],
    [MenuItems],
    [TicketRights],
    [Signature],
    [LinkedIn],
    [OnlyEmailAfterHours],
    [BlockInboundEmail],
    [SalesForceID],
    [ChangeTicketVisibility],
    [ChangeKBVisibility],
    [EnforceSingleSession],
    [NeedsIndexing],
    [AllowAnyTicketCustomer],
    [FontFamily],
    [FontSize],
    [CanCreateCompany],
    [CanEditCompany],
    [CanCreateContact],
    [CanEditContact],
    [RestrictUserFromEditingAnyActions],
    [AllowUserToEditAnyAction],
    [UserCanPinAction],
    [PortalLimitOrgTickets],
    [CanCreateAsset],
    [CanEditAsset],
    [CanChangeCommunityVisibility],
    [FilterInactive],
    [DisableExporting],
    [CanCreateProducts],
    [CanEditProducts],
    [CanCreateVersions],
    [CanEditVersions],
    [ReceiveUnassignedGroupEmails],
    [ProductFamiliesRights],
    [BlockEmailFromCreatingOnly])
  VALUES (
    @Email,
    @FirstName,
    @MiddleName,
    @LastName,
    @Title,
    @CryptedPassword,
    @IsActive,
    @MarkDeleted,
    @TimeZoneID,
    @CultureName,
    @LastLogin,
    @LastActivity,
    @LastPing,
    @LastWaterCoolerID,
    @IsSystemAdmin,
    @IsFinanceAdmin,
    @IsPasswordExpired,
    @IsPortalUser,
    @IsChatUser,
    @PrimaryGroupID,
    @InOffice,
    @InOfficeComment,
    @ReceiveTicketNotifications,
    @ReceiveAllGroupNotifications,
    @SubscribeToNewTickets,
    @ActivatedOn,
    @DeactivatedOn,
    @OrganizationID,
    @LastVersion,
    @SessionID,
    @ImportID,
    @DateCreated,
    @DateModified,
    @CreatorID,
    @ModifierID,
    @OrgsUserCanSeeOnPortal,
    @DoNotAutoSubscribe,
    @IsClassicView,
    @SubscribeToNewActions,
    @ApprovedTerms,
    @ShowWelcomePage,
    @UserInformation,
    @PortalAutoReg,
    @AppChatID,
    @AppChatStatus,
    @MenuItems,
    @TicketRights,
    @Signature,
    @LinkedIn,
    @OnlyEmailAfterHours,
    @BlockInboundEmail,
    @SalesForceID,
    @ChangeTicketVisibility,
    @ChangeKBVisibility,
    @EnforceSingleSession,
    @NeedsIndexing,
    @AllowAnyTicketCustomer,
    @FontFamily,
    @FontSize,
    @CanCreateCompany,
    @CanEditCompany,
    @CanCreateContact,
    @CanEditContact,
    @RestrictUserFromEditingAnyActions,
    @AllowUserToEditAnyAction,
    @UserCanPinAction,
    @PortalLimitOrgTickets,
    @CanCreateAsset,
    @CanEditAsset,
    @CanChangeCommunityVisibility,
    @FilterInactive,
    @DisableExporting,
    @CanCreateProducts,
    @CanEditProducts,
    @CanCreateVersions,
    @CanEditVersions,
    @ReceiveUnassignedGroupEmails,
    @ProductFamiliesRights,
    @BlockEmailFromCreatingOnly)

SET @Identity = SCOPE_IDENTITY()
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedUpdateUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedUpdateUser
GO

CREATE PROCEDURE dbo.uspGeneratedUpdateUser

(
  @UserID int,
  @Email varchar(1024),
  @FirstName varchar(100),
  @MiddleName varchar(100),
  @LastName varchar(100),
  @Title varchar(100),
  @CryptedPassword varchar(255),
  @IsActive bit,
  @MarkDeleted bit,
  @TimeZoneID varchar(300),
  @CultureName varchar(50),
  @LastLogin datetime,
  @LastActivity datetime,
  @LastPing datetime,
  @LastWaterCoolerID int,
  @IsSystemAdmin bit,
  @IsFinanceAdmin bit,
  @IsPasswordExpired bit,
  @IsPortalUser bit,
  @IsChatUser bit,
  @PrimaryGroupID int,
  @InOffice bit,
  @InOfficeComment varchar(200),
  @ReceiveTicketNotifications bit,
  @ReceiveAllGroupNotifications bit,
  @SubscribeToNewTickets bit,
  @ActivatedOn datetime,
  @DeactivatedOn datetime,
  @OrganizationID int,
  @LastVersion varchar(50),
  @SessionID uniqueidentifier,
  @ImportID varchar(500),
  @DateModified datetime,
  @ModifierID int,
  @OrgsUserCanSeeOnPortal varchar(200),
  @DoNotAutoSubscribe bit,
  @IsClassicView bit,
  @SubscribeToNewActions bit,
  @ApprovedTerms bit,
  @ShowWelcomePage bit,
  @UserInformation varchar(MAX),
  @PortalAutoReg bit,
  @AppChatID varchar(200),
  @AppChatStatus bit,
  @MenuItems varchar(1000),
  @TicketRights int,
  @Signature varchar(MAX),
  @LinkedIn varchar(200),
  @OnlyEmailAfterHours bit,
  @BlockInboundEmail bit,
  @SalesForceID varchar(8000),
  @ChangeTicketVisibility bit,
  @ChangeKBVisibility bit,
  @EnforceSingleSession bit,
  @NeedsIndexing bit,
  @AllowAnyTicketCustomer bit,
  @FontFamily int,
  @FontSize int,
  @CanCreateCompany bit,
  @CanEditCompany bit,
  @CanCreateContact bit,
  @CanEditContact bit,
  @RestrictUserFromEditingAnyActions bit,
  @AllowUserToEditAnyAction bit,
  @UserCanPinAction bit,
  @PortalLimitOrgTickets bit,
  @CanCreateAsset bit,
  @CanEditAsset bit,
  @CanChangeCommunityVisibility bit,
  @FilterInactive bit,
  @DisableExporting bit,
  @CanCreateProducts bit,
  @CanEditProducts bit,
  @CanCreateVersions bit,
  @CanEditVersions bit,
  @ReceiveUnassignedGroupEmails bit,
  @ProductFamiliesRights int,
  @BlockEmailFromCreatingOnly bit
)
AS
  SET NOCOUNT OFF;
  UPDATE [dbo].[Users]
  SET
    [Email] = @Email,
    [FirstName] = @FirstName,
    [MiddleName] = @MiddleName,
    [LastName] = @LastName,
    [Title] = @Title,
    [CryptedPassword] = @CryptedPassword,
    [IsActive] = @IsActive,
    [MarkDeleted] = @MarkDeleted,
    [TimeZoneID] = @TimeZoneID,
    [CultureName] = @CultureName,
    [LastLogin] = @LastLogin,
    [LastActivity] = @LastActivity,
    [LastPing] = @LastPing,
    [LastWaterCoolerID] = @LastWaterCoolerID,
    [IsSystemAdmin] = @IsSystemAdmin,
    [IsFinanceAdmin] = @IsFinanceAdmin,
    [IsPasswordExpired] = @IsPasswordExpired,
    [IsPortalUser] = @IsPortalUser,
    [IsChatUser] = @IsChatUser,
    [PrimaryGroupID] = @PrimaryGroupID,
    [InOffice] = @InOffice,
    [InOfficeComment] = @InOfficeComment,
    [ReceiveTicketNotifications] = @ReceiveTicketNotifications,
    [ReceiveAllGroupNotifications] = @ReceiveAllGroupNotifications,
    [SubscribeToNewTickets] = @SubscribeToNewTickets,
    [ActivatedOn] = @ActivatedOn,
    [DeactivatedOn] = @DeactivatedOn,
    [OrganizationID] = @OrganizationID,
    [LastVersion] = @LastVersion,
    [SessionID] = @SessionID,
    [ImportID] = @ImportID,
    [DateModified] = @DateModified,
    [ModifierID] = @ModifierID,
    [OrgsUserCanSeeOnPortal] = @OrgsUserCanSeeOnPortal,
    [DoNotAutoSubscribe] = @DoNotAutoSubscribe,
    [IsClassicView] = @IsClassicView,
    [SubscribeToNewActions] = @SubscribeToNewActions,
    [ApprovedTerms] = @ApprovedTerms,
    [ShowWelcomePage] = @ShowWelcomePage,
    [UserInformation] = @UserInformation,
    [PortalAutoReg] = @PortalAutoReg,
    [AppChatID] = @AppChatID,
    [AppChatStatus] = @AppChatStatus,
    [MenuItems] = @MenuItems,
    [TicketRights] = @TicketRights,
    [Signature] = @Signature,
    [LinkedIn] = @LinkedIn,
    [OnlyEmailAfterHours] = @OnlyEmailAfterHours,
    [BlockInboundEmail] = @BlockInboundEmail,
    [SalesForceID] = @SalesForceID,
    [ChangeTicketVisibility] = @ChangeTicketVisibility,
    [ChangeKBVisibility] = @ChangeKBVisibility,
    [EnforceSingleSession] = @EnforceSingleSession,
    [NeedsIndexing] = @NeedsIndexing,
    [AllowAnyTicketCustomer] = @AllowAnyTicketCustomer,
    [FontFamily] = @FontFamily,
    [FontSize] = @FontSize,
    [CanCreateCompany] = @CanCreateCompany,
    [CanEditCompany] = @CanEditCompany,
    [CanCreateContact] = @CanCreateContact,
    [CanEditContact] = @CanEditContact,
    [RestrictUserFromEditingAnyActions] = @RestrictUserFromEditingAnyActions,
    [AllowUserToEditAnyAction] = @AllowUserToEditAnyAction,
    [UserCanPinAction] = @UserCanPinAction,
    [PortalLimitOrgTickets] = @PortalLimitOrgTickets,
    [CanCreateAsset] = @CanCreateAsset,
    [CanEditAsset] = @CanEditAsset,
    [CanChangeCommunityVisibility] = @CanChangeCommunityVisibility,
    [FilterInactive] = @FilterInactive,
    [DisableExporting] = @DisableExporting,
    [CanCreateProducts] = @CanCreateProducts,
    [CanEditProducts] = @CanEditProducts,
    [CanCreateVersions] = @CanCreateVersions,
    [CanEditVersions] = @CanEditVersions,
    [ReceiveUnassignedGroupEmails] = @ReceiveUnassignedGroupEmails,
    [ProductFamiliesRights] = @ProductFamiliesRights,
    [BlockEmailFromCreatingOnly] = @BlockEmailFromCreatingOnly
  WHERE ([UserID] = @UserID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedDeleteUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedDeleteUser
GO

CREATE PROCEDURE dbo.uspGeneratedDeleteUser

(
  @UserID int
)
AS
  SET NOCOUNT OFF;
  DELETE FROM [dbo].[Users]
  WHERE ([UserID] = @UserID)
GO


IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedSelectUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedSelectUser
GO

CREATE PROCEDURE dbo.uspGeneratedSelectUser

(
  @UserID int
)
AS
  SET NOCOUNT OFF;
  SELECT
    [UserID],
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [Title],
    [CryptedPassword],
    [IsActive],
    [MarkDeleted],
    [TimeZoneID],
    [CultureName],
    [LastLogin],
    [LastActivity],
    [LastPing],
    [LastWaterCoolerID],
    [IsSystemAdmin],
    [IsFinanceAdmin],
    [IsPasswordExpired],
    [IsPortalUser],
    [IsChatUser],
    [PrimaryGroupID],
    [InOffice],
    [InOfficeComment],
    [ReceiveTicketNotifications],
    [ReceiveAllGroupNotifications],
    [SubscribeToNewTickets],
    [ActivatedOn],
    [DeactivatedOn],
    [OrganizationID],
    [LastVersion],
    [SessionID],
    [ImportID],
    [DateCreated],
    [DateModified],
    [CreatorID],
    [ModifierID],
    [OrgsUserCanSeeOnPortal],
    [DoNotAutoSubscribe],
    [IsClassicView],
    [SubscribeToNewActions],
    [ApprovedTerms],
    [ShowWelcomePage],
    [UserInformation],
    [PortalAutoReg],
    [AppChatID],
    [AppChatStatus],
    [MenuItems],
    [TicketRights],
    [Signature],
    [LinkedIn],
    [OnlyEmailAfterHours],
    [BlockInboundEmail],
    [SalesForceID],
    [ChangeTicketVisibility],
    [ChangeKBVisibility],
    [EnforceSingleSession],
    [NeedsIndexing],
    [AllowAnyTicketCustomer],
    [FontFamily],
    [FontSize],
    [CanCreateCompany],
    [CanEditCompany],
    [CanCreateContact],
    [CanEditContact],
    [RestrictUserFromEditingAnyActions],
    [AllowUserToEditAnyAction],
    [UserCanPinAction],
    [PortalLimitOrgTickets],
    [CanCreateAsset],
    [CanEditAsset],
    [CanChangeCommunityVisibility],
    [FilterInactive],
    [DisableExporting],
    [CanCreateProducts],
    [CanEditProducts],
    [CanCreateVersions],
    [CanEditVersions],
    [ReceiveUnassignedGroupEmails],
    [ProductFamiliesRights],
    [BlockEmailFromCreatingOnly]
  FROM [dbo].[Users]
  WHERE ([UserID] = @UserID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedInsertUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedInsertUser
GO

CREATE PROCEDURE dbo.uspGeneratedInsertUser

(
  @Email varchar(1024),
  @FirstName varchar(100),
  @MiddleName varchar(100),
  @LastName varchar(100),
  @Title varchar(100),
  @CryptedPassword varchar(255),
  @IsActive bit,
  @MarkDeleted bit,
  @TimeZoneID varchar(300),
  @CultureName varchar(50),
  @LastLogin datetime,
  @LastActivity datetime,
  @LastPing datetime,
  @LastWaterCoolerID int,
  @IsSystemAdmin bit,
  @IsFinanceAdmin bit,
  @IsPasswordExpired bit,
  @IsPortalUser bit,
  @IsChatUser bit,
  @PrimaryGroupID int,
  @InOffice bit,
  @InOfficeComment varchar(200),
  @ReceiveTicketNotifications bit,
  @ReceiveAllGroupNotifications bit,
  @SubscribeToNewTickets bit,
  @ActivatedOn datetime,
  @DeactivatedOn datetime,
  @OrganizationID int,
  @LastVersion varchar(50),
  @SessionID uniqueidentifier,
  @ImportID varchar(500),
  @DateCreated datetime,
  @DateModified datetime,
  @CreatorID int,
  @ModifierID int,
  @OrgsUserCanSeeOnPortal varchar(200),
  @DoNotAutoSubscribe bit,
  @IsClassicView bit,
  @SubscribeToNewActions bit,
  @ApprovedTerms bit,
  @ShowWelcomePage bit,
  @UserInformation varchar(MAX),
  @PortalAutoReg bit,
  @AppChatID varchar(200),
  @AppChatStatus bit,
  @MenuItems varchar(1000),
  @TicketRights int,
  @Signature varchar(MAX),
  @LinkedIn varchar(200),
  @OnlyEmailAfterHours bit,
  @BlockInboundEmail bit,
  @SalesForceID varchar(8000),
  @ChangeTicketVisibility bit,
  @ChangeKBVisibility bit,
  @EnforceSingleSession bit,
  @NeedsIndexing bit,
  @AllowAnyTicketCustomer bit,
  @FontFamily int,
  @FontSize int,
  @CanCreateCompany bit,
  @CanEditCompany bit,
  @CanCreateContact bit,
  @CanEditContact bit,
  @RestrictUserFromEditingAnyActions bit,
  @AllowUserToEditAnyAction bit,
  @UserCanPinAction bit,
  @PortalLimitOrgTickets bit,
  @CanCreateAsset bit,
  @CanEditAsset bit,
  @CanChangeCommunityVisibility bit,
  @FilterInactive bit,
  @DisableExporting bit,
  @CanCreateProducts bit,
  @CanEditProducts bit,
  @CanCreateVersions bit,
  @CanEditVersions bit,
  @ReceiveUnassignedGroupEmails bit,
  @ProductFamiliesRights int,
  @BlockEmailFromCreatingOnly bit,
  @Identity int OUT
)
AS
  SET NOCOUNT OFF;
  INSERT INTO [dbo].[Users]
  (
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [Title],
    [CryptedPassword],
    [IsActive],
    [MarkDeleted],
    [TimeZoneID],
    [CultureName],
    [LastLogin],
    [LastActivity],
    [LastPing],
    [LastWaterCoolerID],
    [IsSystemAdmin],
    [IsFinanceAdmin],
    [IsPasswordExpired],
    [IsPortalUser],
    [IsChatUser],
    [PrimaryGroupID],
    [InOffice],
    [InOfficeComment],
    [ReceiveTicketNotifications],
    [ReceiveAllGroupNotifications],
    [SubscribeToNewTickets],
    [ActivatedOn],
    [DeactivatedOn],
    [OrganizationID],
    [LastVersion],
    [SessionID],
    [ImportID],
    [DateCreated],
    [DateModified],
    [CreatorID],
    [ModifierID],
    [OrgsUserCanSeeOnPortal],
    [DoNotAutoSubscribe],
    [IsClassicView],
    [SubscribeToNewActions],
    [ApprovedTerms],
    [ShowWelcomePage],
    [UserInformation],
    [PortalAutoReg],
    [AppChatID],
    [AppChatStatus],
    [MenuItems],
    [TicketRights],
    [Signature],
    [LinkedIn],
    [OnlyEmailAfterHours],
    [BlockInboundEmail],
    [SalesForceID],
    [ChangeTicketVisibility],
    [ChangeKBVisibility],
    [EnforceSingleSession],
    [NeedsIndexing],
    [AllowAnyTicketCustomer],
    [FontFamily],
    [FontSize],
    [CanCreateCompany],
    [CanEditCompany],
    [CanCreateContact],
    [CanEditContact],
    [RestrictUserFromEditingAnyActions],
    [AllowUserToEditAnyAction],
    [UserCanPinAction],
    [PortalLimitOrgTickets],
    [CanCreateAsset],
    [CanEditAsset],
    [CanChangeCommunityVisibility],
    [FilterInactive],
    [DisableExporting],
    [CanCreateProducts],
    [CanEditProducts],
    [CanCreateVersions],
    [CanEditVersions],
    [ReceiveUnassignedGroupEmails],
    [ProductFamiliesRights],
    [BlockEmailFromCreatingOnly])
  VALUES (
    @Email,
    @FirstName,
    @MiddleName,
    @LastName,
    @Title,
    @CryptedPassword,
    @IsActive,
    @MarkDeleted,
    @TimeZoneID,
    @CultureName,
    @LastLogin,
    @LastActivity,
    @LastPing,
    @LastWaterCoolerID,
    @IsSystemAdmin,
    @IsFinanceAdmin,
    @IsPasswordExpired,
    @IsPortalUser,
    @IsChatUser,
    @PrimaryGroupID,
    @InOffice,
    @InOfficeComment,
    @ReceiveTicketNotifications,
    @ReceiveAllGroupNotifications,
    @SubscribeToNewTickets,
    @ActivatedOn,
    @DeactivatedOn,
    @OrganizationID,
    @LastVersion,
    @SessionID,
    @ImportID,
    @DateCreated,
    @DateModified,
    @CreatorID,
    @ModifierID,
    @OrgsUserCanSeeOnPortal,
    @DoNotAutoSubscribe,
    @IsClassicView,
    @SubscribeToNewActions,
    @ApprovedTerms,
    @ShowWelcomePage,
    @UserInformation,
    @PortalAutoReg,
    @AppChatID,
    @AppChatStatus,
    @MenuItems,
    @TicketRights,
    @Signature,
    @LinkedIn,
    @OnlyEmailAfterHours,
    @BlockInboundEmail,
    @SalesForceID,
    @ChangeTicketVisibility,
    @ChangeKBVisibility,
    @EnforceSingleSession,
    @NeedsIndexing,
    @AllowAnyTicketCustomer,
    @FontFamily,
    @FontSize,
    @CanCreateCompany,
    @CanEditCompany,
    @CanCreateContact,
    @CanEditContact,
    @RestrictUserFromEditingAnyActions,
    @AllowUserToEditAnyAction,
    @UserCanPinAction,
    @PortalLimitOrgTickets,
    @CanCreateAsset,
    @CanEditAsset,
    @CanChangeCommunityVisibility,
    @FilterInactive,
    @DisableExporting,
    @CanCreateProducts,
    @CanEditProducts,
    @CanCreateVersions,
    @CanEditVersions,
    @ReceiveUnassignedGroupEmails,
    @ProductFamiliesRights,
    @BlockEmailFromCreatingOnly)

SET @Identity = SCOPE_IDENTITY()
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedUpdateUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedUpdateUser
GO

CREATE PROCEDURE dbo.uspGeneratedUpdateUser

(
  @UserID int,
  @Email varchar(1024),
  @FirstName varchar(100),
  @MiddleName varchar(100),
  @LastName varchar(100),
  @Title varchar(100),
  @CryptedPassword varchar(255),
  @IsActive bit,
  @MarkDeleted bit,
  @TimeZoneID varchar(300),
  @CultureName varchar(50),
  @LastLogin datetime,
  @LastActivity datetime,
  @LastPing datetime,
  @LastWaterCoolerID int,
  @IsSystemAdmin bit,
  @IsFinanceAdmin bit,
  @IsPasswordExpired bit,
  @IsPortalUser bit,
  @IsChatUser bit,
  @PrimaryGroupID int,
  @InOffice bit,
  @InOfficeComment varchar(200),
  @ReceiveTicketNotifications bit,
  @ReceiveAllGroupNotifications bit,
  @SubscribeToNewTickets bit,
  @ActivatedOn datetime,
  @DeactivatedOn datetime,
  @OrganizationID int,
  @LastVersion varchar(50),
  @SessionID uniqueidentifier,
  @ImportID varchar(500),
  @DateModified datetime,
  @ModifierID int,
  @OrgsUserCanSeeOnPortal varchar(200),
  @DoNotAutoSubscribe bit,
  @IsClassicView bit,
  @SubscribeToNewActions bit,
  @ApprovedTerms bit,
  @ShowWelcomePage bit,
  @UserInformation varchar(MAX),
  @PortalAutoReg bit,
  @AppChatID varchar(200),
  @AppChatStatus bit,
  @MenuItems varchar(1000),
  @TicketRights int,
  @Signature varchar(MAX),
  @LinkedIn varchar(200),
  @OnlyEmailAfterHours bit,
  @BlockInboundEmail bit,
  @SalesForceID varchar(8000),
  @ChangeTicketVisibility bit,
  @ChangeKBVisibility bit,
  @EnforceSingleSession bit,
  @NeedsIndexing bit,
  @AllowAnyTicketCustomer bit,
  @FontFamily int,
  @FontSize int,
  @CanCreateCompany bit,
  @CanEditCompany bit,
  @CanCreateContact bit,
  @CanEditContact bit,
  @RestrictUserFromEditingAnyActions bit,
  @AllowUserToEditAnyAction bit,
  @UserCanPinAction bit,
  @PortalLimitOrgTickets bit,
  @CanCreateAsset bit,
  @CanEditAsset bit,
  @CanChangeCommunityVisibility bit,
  @FilterInactive bit,
  @DisableExporting bit,
  @CanCreateProducts bit,
  @CanEditProducts bit,
  @CanCreateVersions bit,
  @CanEditVersions bit,
  @ReceiveUnassignedGroupEmails bit,
  @ProductFamiliesRights int,
  @BlockEmailFromCreatingOnly bit
)
AS
  SET NOCOUNT OFF;
  UPDATE [dbo].[Users]
  SET
    [Email] = @Email,
    [FirstName] = @FirstName,
    [MiddleName] = @MiddleName,
    [LastName] = @LastName,
    [Title] = @Title,
    [CryptedPassword] = @CryptedPassword,
    [IsActive] = @IsActive,
    [MarkDeleted] = @MarkDeleted,
    [TimeZoneID] = @TimeZoneID,
    [CultureName] = @CultureName,
    [LastLogin] = @LastLogin,
    [LastActivity] = @LastActivity,
    [LastPing] = @LastPing,
    [LastWaterCoolerID] = @LastWaterCoolerID,
    [IsSystemAdmin] = @IsSystemAdmin,
    [IsFinanceAdmin] = @IsFinanceAdmin,
    [IsPasswordExpired] = @IsPasswordExpired,
    [IsPortalUser] = @IsPortalUser,
    [IsChatUser] = @IsChatUser,
    [PrimaryGroupID] = @PrimaryGroupID,
    [InOffice] = @InOffice,
    [InOfficeComment] = @InOfficeComment,
    [ReceiveTicketNotifications] = @ReceiveTicketNotifications,
    [ReceiveAllGroupNotifications] = @ReceiveAllGroupNotifications,
    [SubscribeToNewTickets] = @SubscribeToNewTickets,
    [ActivatedOn] = @ActivatedOn,
    [DeactivatedOn] = @DeactivatedOn,
    [OrganizationID] = @OrganizationID,
    [LastVersion] = @LastVersion,
    [SessionID] = @SessionID,
    [ImportID] = @ImportID,
    [DateModified] = @DateModified,
    [ModifierID] = @ModifierID,
    [OrgsUserCanSeeOnPortal] = @OrgsUserCanSeeOnPortal,
    [DoNotAutoSubscribe] = @DoNotAutoSubscribe,
    [IsClassicView] = @IsClassicView,
    [SubscribeToNewActions] = @SubscribeToNewActions,
    [ApprovedTerms] = @ApprovedTerms,
    [ShowWelcomePage] = @ShowWelcomePage,
    [UserInformation] = @UserInformation,
    [PortalAutoReg] = @PortalAutoReg,
    [AppChatID] = @AppChatID,
    [AppChatStatus] = @AppChatStatus,
    [MenuItems] = @MenuItems,
    [TicketRights] = @TicketRights,
    [Signature] = @Signature,
    [LinkedIn] = @LinkedIn,
    [OnlyEmailAfterHours] = @OnlyEmailAfterHours,
    [BlockInboundEmail] = @BlockInboundEmail,
    [SalesForceID] = @SalesForceID,
    [ChangeTicketVisibility] = @ChangeTicketVisibility,
    [ChangeKBVisibility] = @ChangeKBVisibility,
    [EnforceSingleSession] = @EnforceSingleSession,
    [NeedsIndexing] = @NeedsIndexing,
    [AllowAnyTicketCustomer] = @AllowAnyTicketCustomer,
    [FontFamily] = @FontFamily,
    [FontSize] = @FontSize,
    [CanCreateCompany] = @CanCreateCompany,
    [CanEditCompany] = @CanEditCompany,
    [CanCreateContact] = @CanCreateContact,
    [CanEditContact] = @CanEditContact,
    [RestrictUserFromEditingAnyActions] = @RestrictUserFromEditingAnyActions,
    [AllowUserToEditAnyAction] = @AllowUserToEditAnyAction,
    [UserCanPinAction] = @UserCanPinAction,
    [PortalLimitOrgTickets] = @PortalLimitOrgTickets,
    [CanCreateAsset] = @CanCreateAsset,
    [CanEditAsset] = @CanEditAsset,
    [CanChangeCommunityVisibility] = @CanChangeCommunityVisibility,
    [FilterInactive] = @FilterInactive,
    [DisableExporting] = @DisableExporting,
    [CanCreateProducts] = @CanCreateProducts,
    [CanEditProducts] = @CanEditProducts,
    [CanCreateVersions] = @CanCreateVersions,
    [CanEditVersions] = @CanEditVersions,
    [ReceiveUnassignedGroupEmails] = @ReceiveUnassignedGroupEmails,
    [ProductFamiliesRights] = @ProductFamiliesRights,
    [BlockEmailFromCreatingOnly] = @BlockEmailFromCreatingOnly
  WHERE ([UserID] = @UserID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedDeleteUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedDeleteUser
GO

CREATE PROCEDURE dbo.uspGeneratedDeleteUser

(
  @UserID int
)
AS
  SET NOCOUNT OFF;
  DELETE FROM [dbo].[Users]
  WHERE ([UserID] = @UserID)
GO


IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedSelectUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedSelectUser
GO

CREATE PROCEDURE dbo.uspGeneratedSelectUser

(
  @UserID int
)
AS
  SET NOCOUNT OFF;
  SELECT
    [UserID],
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [Title],
    [CryptedPassword],
    [IsActive],
    [MarkDeleted],
    [TimeZoneID],
    [CultureName],
    [LastLogin],
    [LastActivity],
    [LastPing],
    [LastWaterCoolerID],
    [IsSystemAdmin],
    [IsFinanceAdmin],
    [IsPasswordExpired],
    [IsPortalUser],
    [IsChatUser],
    [PrimaryGroupID],
    [InOffice],
    [InOfficeComment],
    [ReceiveTicketNotifications],
    [ReceiveAllGroupNotifications],
    [SubscribeToNewTickets],
    [ActivatedOn],
    [DeactivatedOn],
    [OrganizationID],
    [LastVersion],
    [SessionID],
    [ImportID],
    [DateCreated],
    [DateModified],
    [CreatorID],
    [ModifierID],
    [OrgsUserCanSeeOnPortal],
    [DoNotAutoSubscribe],
    [IsClassicView],
    [SubscribeToNewActions],
    [ApprovedTerms],
    [ShowWelcomePage],
    [UserInformation],
    [PortalAutoReg],
    [AppChatID],
    [AppChatStatus],
    [MenuItems],
    [TicketRights],
    [Signature],
    [LinkedIn],
    [OnlyEmailAfterHours],
    [BlockInboundEmail],
    [SalesForceID],
    [ChangeTicketVisibility],
    [ChangeKBVisibility],
    [EnforceSingleSession],
    [NeedsIndexing],
    [AllowAnyTicketCustomer],
    [FontFamily],
    [FontSize],
    [CanCreateCompany],
    [CanEditCompany],
    [CanCreateContact],
    [CanEditContact],
    [RestrictUserFromEditingAnyActions],
    [AllowUserToEditAnyAction],
    [UserCanPinAction],
    [PortalLimitOrgTickets],
    [CanCreateAsset],
    [CanEditAsset],
    [CanChangeCommunityVisibility],
    [FilterInactive],
    [DisableExporting],
    [CanCreateProducts],
    [CanEditProducts],
    [CanCreateVersions],
    [CanEditVersions],
    [ReceiveUnassignedGroupEmails],
    [ProductFamiliesRights],
    [BlockEmailFromCreatingOnly]
  FROM [dbo].[Users]
  WHERE ([UserID] = @UserID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedInsertUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedInsertUser
GO

CREATE PROCEDURE dbo.uspGeneratedInsertUser

(
  @Email varchar(1024),
  @FirstName varchar(100),
  @MiddleName varchar(100),
  @LastName varchar(100),
  @Title varchar(100),
  @CryptedPassword varchar(255),
  @IsActive bit,
  @MarkDeleted bit,
  @TimeZoneID varchar(300),
  @CultureName varchar(50),
  @LastLogin datetime,
  @LastActivity datetime,
  @LastPing datetime,
  @LastWaterCoolerID int,
  @IsSystemAdmin bit,
  @IsFinanceAdmin bit,
  @IsPasswordExpired bit,
  @IsPortalUser bit,
  @IsChatUser bit,
  @PrimaryGroupID int,
  @InOffice bit,
  @InOfficeComment varchar(200),
  @ReceiveTicketNotifications bit,
  @ReceiveAllGroupNotifications bit,
  @SubscribeToNewTickets bit,
  @ActivatedOn datetime,
  @DeactivatedOn datetime,
  @OrganizationID int,
  @LastVersion varchar(50),
  @SessionID uniqueidentifier,
  @ImportID varchar(500),
  @DateCreated datetime,
  @DateModified datetime,
  @CreatorID int,
  @ModifierID int,
  @OrgsUserCanSeeOnPortal varchar(200),
  @DoNotAutoSubscribe bit,
  @IsClassicView bit,
  @SubscribeToNewActions bit,
  @ApprovedTerms bit,
  @ShowWelcomePage bit,
  @UserInformation varchar(MAX),
  @PortalAutoReg bit,
  @AppChatID varchar(200),
  @AppChatStatus bit,
  @MenuItems varchar(1000),
  @TicketRights int,
  @Signature varchar(MAX),
  @LinkedIn varchar(200),
  @OnlyEmailAfterHours bit,
  @BlockInboundEmail bit,
  @SalesForceID varchar(8000),
  @ChangeTicketVisibility bit,
  @ChangeKBVisibility bit,
  @EnforceSingleSession bit,
  @NeedsIndexing bit,
  @AllowAnyTicketCustomer bit,
  @FontFamily int,
  @FontSize int,
  @CanCreateCompany bit,
  @CanEditCompany bit,
  @CanCreateContact bit,
  @CanEditContact bit,
  @RestrictUserFromEditingAnyActions bit,
  @AllowUserToEditAnyAction bit,
  @UserCanPinAction bit,
  @PortalLimitOrgTickets bit,
  @CanCreateAsset bit,
  @CanEditAsset bit,
  @CanChangeCommunityVisibility bit,
  @FilterInactive bit,
  @DisableExporting bit,
  @CanCreateProducts bit,
  @CanEditProducts bit,
  @CanCreateVersions bit,
  @CanEditVersions bit,
  @ReceiveUnassignedGroupEmails bit,
  @ProductFamiliesRights int,
  @BlockEmailFromCreatingOnly bit,
  @Identity int OUT
)
AS
  SET NOCOUNT OFF;
  INSERT INTO [dbo].[Users]
  (
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [Title],
    [CryptedPassword],
    [IsActive],
    [MarkDeleted],
    [TimeZoneID],
    [CultureName],
    [LastLogin],
    [LastActivity],
    [LastPing],
    [LastWaterCoolerID],
    [IsSystemAdmin],
    [IsFinanceAdmin],
    [IsPasswordExpired],
    [IsPortalUser],
    [IsChatUser],
    [PrimaryGroupID],
    [InOffice],
    [InOfficeComment],
    [ReceiveTicketNotifications],
    [ReceiveAllGroupNotifications],
    [SubscribeToNewTickets],
    [ActivatedOn],
    [DeactivatedOn],
    [OrganizationID],
    [LastVersion],
    [SessionID],
    [ImportID],
    [DateCreated],
    [DateModified],
    [CreatorID],
    [ModifierID],
    [OrgsUserCanSeeOnPortal],
    [DoNotAutoSubscribe],
    [IsClassicView],
    [SubscribeToNewActions],
    [ApprovedTerms],
    [ShowWelcomePage],
    [UserInformation],
    [PortalAutoReg],
    [AppChatID],
    [AppChatStatus],
    [MenuItems],
    [TicketRights],
    [Signature],
    [LinkedIn],
    [OnlyEmailAfterHours],
    [BlockInboundEmail],
    [SalesForceID],
    [ChangeTicketVisibility],
    [ChangeKBVisibility],
    [EnforceSingleSession],
    [NeedsIndexing],
    [AllowAnyTicketCustomer],
    [FontFamily],
    [FontSize],
    [CanCreateCompany],
    [CanEditCompany],
    [CanCreateContact],
    [CanEditContact],
    [RestrictUserFromEditingAnyActions],
    [AllowUserToEditAnyAction],
    [UserCanPinAction],
    [PortalLimitOrgTickets],
    [CanCreateAsset],
    [CanEditAsset],
    [CanChangeCommunityVisibility],
    [FilterInactive],
    [DisableExporting],
    [CanCreateProducts],
    [CanEditProducts],
    [CanCreateVersions],
    [CanEditVersions],
    [ReceiveUnassignedGroupEmails],
    [ProductFamiliesRights],
    [BlockEmailFromCreatingOnly])
  VALUES (
    @Email,
    @FirstName,
    @MiddleName,
    @LastName,
    @Title,
    @CryptedPassword,
    @IsActive,
    @MarkDeleted,
    @TimeZoneID,
    @CultureName,
    @LastLogin,
    @LastActivity,
    @LastPing,
    @LastWaterCoolerID,
    @IsSystemAdmin,
    @IsFinanceAdmin,
    @IsPasswordExpired,
    @IsPortalUser,
    @IsChatUser,
    @PrimaryGroupID,
    @InOffice,
    @InOfficeComment,
    @ReceiveTicketNotifications,
    @ReceiveAllGroupNotifications,
    @SubscribeToNewTickets,
    @ActivatedOn,
    @DeactivatedOn,
    @OrganizationID,
    @LastVersion,
    @SessionID,
    @ImportID,
    @DateCreated,
    @DateModified,
    @CreatorID,
    @ModifierID,
    @OrgsUserCanSeeOnPortal,
    @DoNotAutoSubscribe,
    @IsClassicView,
    @SubscribeToNewActions,
    @ApprovedTerms,
    @ShowWelcomePage,
    @UserInformation,
    @PortalAutoReg,
    @AppChatID,
    @AppChatStatus,
    @MenuItems,
    @TicketRights,
    @Signature,
    @LinkedIn,
    @OnlyEmailAfterHours,
    @BlockInboundEmail,
    @SalesForceID,
    @ChangeTicketVisibility,
    @ChangeKBVisibility,
    @EnforceSingleSession,
    @NeedsIndexing,
    @AllowAnyTicketCustomer,
    @FontFamily,
    @FontSize,
    @CanCreateCompany,
    @CanEditCompany,
    @CanCreateContact,
    @CanEditContact,
    @RestrictUserFromEditingAnyActions,
    @AllowUserToEditAnyAction,
    @UserCanPinAction,
    @PortalLimitOrgTickets,
    @CanCreateAsset,
    @CanEditAsset,
    @CanChangeCommunityVisibility,
    @FilterInactive,
    @DisableExporting,
    @CanCreateProducts,
    @CanEditProducts,
    @CanCreateVersions,
    @CanEditVersions,
    @ReceiveUnassignedGroupEmails,
    @ProductFamiliesRights,
    @BlockEmailFromCreatingOnly)

SET @Identity = SCOPE_IDENTITY()
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedUpdateUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedUpdateUser
GO

CREATE PROCEDURE dbo.uspGeneratedUpdateUser

(
  @UserID int,
  @Email varchar(1024),
  @FirstName varchar(100),
  @MiddleName varchar(100),
  @LastName varchar(100),
  @Title varchar(100),
  @CryptedPassword varchar(255),
  @IsActive bit,
  @MarkDeleted bit,
  @TimeZoneID varchar(300),
  @CultureName varchar(50),
  @LastLogin datetime,
  @LastActivity datetime,
  @LastPing datetime,
  @LastWaterCoolerID int,
  @IsSystemAdmin bit,
  @IsFinanceAdmin bit,
  @IsPasswordExpired bit,
  @IsPortalUser bit,
  @IsChatUser bit,
  @PrimaryGroupID int,
  @InOffice bit,
  @InOfficeComment varchar(200),
  @ReceiveTicketNotifications bit,
  @ReceiveAllGroupNotifications bit,
  @SubscribeToNewTickets bit,
  @ActivatedOn datetime,
  @DeactivatedOn datetime,
  @OrganizationID int,
  @LastVersion varchar(50),
  @SessionID uniqueidentifier,
  @ImportID varchar(500),
  @DateModified datetime,
  @ModifierID int,
  @OrgsUserCanSeeOnPortal varchar(200),
  @DoNotAutoSubscribe bit,
  @IsClassicView bit,
  @SubscribeToNewActions bit,
  @ApprovedTerms bit,
  @ShowWelcomePage bit,
  @UserInformation varchar(MAX),
  @PortalAutoReg bit,
  @AppChatID varchar(200),
  @AppChatStatus bit,
  @MenuItems varchar(1000),
  @TicketRights int,
  @Signature varchar(MAX),
  @LinkedIn varchar(200),
  @OnlyEmailAfterHours bit,
  @BlockInboundEmail bit,
  @SalesForceID varchar(8000),
  @ChangeTicketVisibility bit,
  @ChangeKBVisibility bit,
  @EnforceSingleSession bit,
  @NeedsIndexing bit,
  @AllowAnyTicketCustomer bit,
  @FontFamily int,
  @FontSize int,
  @CanCreateCompany bit,
  @CanEditCompany bit,
  @CanCreateContact bit,
  @CanEditContact bit,
  @RestrictUserFromEditingAnyActions bit,
  @AllowUserToEditAnyAction bit,
  @UserCanPinAction bit,
  @PortalLimitOrgTickets bit,
  @CanCreateAsset bit,
  @CanEditAsset bit,
  @CanChangeCommunityVisibility bit,
  @FilterInactive bit,
  @DisableExporting bit,
  @CanCreateProducts bit,
  @CanEditProducts bit,
  @CanCreateVersions bit,
  @CanEditVersions bit,
  @ReceiveUnassignedGroupEmails bit,
  @ProductFamiliesRights int,
  @BlockEmailFromCreatingOnly bit
)
AS
  SET NOCOUNT OFF;
  UPDATE [dbo].[Users]
  SET
    [Email] = @Email,
    [FirstName] = @FirstName,
    [MiddleName] = @MiddleName,
    [LastName] = @LastName,
    [Title] = @Title,
    [CryptedPassword] = @CryptedPassword,
    [IsActive] = @IsActive,
    [MarkDeleted] = @MarkDeleted,
    [TimeZoneID] = @TimeZoneID,
    [CultureName] = @CultureName,
    [LastLogin] = @LastLogin,
    [LastActivity] = @LastActivity,
    [LastPing] = @LastPing,
    [LastWaterCoolerID] = @LastWaterCoolerID,
    [IsSystemAdmin] = @IsSystemAdmin,
    [IsFinanceAdmin] = @IsFinanceAdmin,
    [IsPasswordExpired] = @IsPasswordExpired,
    [IsPortalUser] = @IsPortalUser,
    [IsChatUser] = @IsChatUser,
    [PrimaryGroupID] = @PrimaryGroupID,
    [InOffice] = @InOffice,
    [InOfficeComment] = @InOfficeComment,
    [ReceiveTicketNotifications] = @ReceiveTicketNotifications,
    [ReceiveAllGroupNotifications] = @ReceiveAllGroupNotifications,
    [SubscribeToNewTickets] = @SubscribeToNewTickets,
    [ActivatedOn] = @ActivatedOn,
    [DeactivatedOn] = @DeactivatedOn,
    [OrganizationID] = @OrganizationID,
    [LastVersion] = @LastVersion,
    [SessionID] = @SessionID,
    [ImportID] = @ImportID,
    [DateModified] = @DateModified,
    [ModifierID] = @ModifierID,
    [OrgsUserCanSeeOnPortal] = @OrgsUserCanSeeOnPortal,
    [DoNotAutoSubscribe] = @DoNotAutoSubscribe,
    [IsClassicView] = @IsClassicView,
    [SubscribeToNewActions] = @SubscribeToNewActions,
    [ApprovedTerms] = @ApprovedTerms,
    [ShowWelcomePage] = @ShowWelcomePage,
    [UserInformation] = @UserInformation,
    [PortalAutoReg] = @PortalAutoReg,
    [AppChatID] = @AppChatID,
    [AppChatStatus] = @AppChatStatus,
    [MenuItems] = @MenuItems,
    [TicketRights] = @TicketRights,
    [Signature] = @Signature,
    [LinkedIn] = @LinkedIn,
    [OnlyEmailAfterHours] = @OnlyEmailAfterHours,
    [BlockInboundEmail] = @BlockInboundEmail,
    [SalesForceID] = @SalesForceID,
    [ChangeTicketVisibility] = @ChangeTicketVisibility,
    [ChangeKBVisibility] = @ChangeKBVisibility,
    [EnforceSingleSession] = @EnforceSingleSession,
    [NeedsIndexing] = @NeedsIndexing,
    [AllowAnyTicketCustomer] = @AllowAnyTicketCustomer,
    [FontFamily] = @FontFamily,
    [FontSize] = @FontSize,
    [CanCreateCompany] = @CanCreateCompany,
    [CanEditCompany] = @CanEditCompany,
    [CanCreateContact] = @CanCreateContact,
    [CanEditContact] = @CanEditContact,
    [RestrictUserFromEditingAnyActions] = @RestrictUserFromEditingAnyActions,
    [AllowUserToEditAnyAction] = @AllowUserToEditAnyAction,
    [UserCanPinAction] = @UserCanPinAction,
    [PortalLimitOrgTickets] = @PortalLimitOrgTickets,
    [CanCreateAsset] = @CanCreateAsset,
    [CanEditAsset] = @CanEditAsset,
    [CanChangeCommunityVisibility] = @CanChangeCommunityVisibility,
    [FilterInactive] = @FilterInactive,
    [DisableExporting] = @DisableExporting,
    [CanCreateProducts] = @CanCreateProducts,
    [CanEditProducts] = @CanEditProducts,
    [CanCreateVersions] = @CanCreateVersions,
    [CanEditVersions] = @CanEditVersions,
    [ReceiveUnassignedGroupEmails] = @ReceiveUnassignedGroupEmails,
    [ProductFamiliesRights] = @ProductFamiliesRights,
    [BlockEmailFromCreatingOnly] = @BlockEmailFromCreatingOnly
  WHERE ([UserID] = @UserID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedDeleteUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedDeleteUser
GO

CREATE PROCEDURE dbo.uspGeneratedDeleteUser

(
  @UserID int
)
AS
  SET NOCOUNT OFF;
  DELETE FROM [dbo].[Users]
  WHERE ([UserID] = @UserID)
GO


IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedSelectUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedSelectUser
GO

CREATE PROCEDURE dbo.uspGeneratedSelectUser

(
  @UserID int
)
AS
  SET NOCOUNT OFF;
  SELECT
    [UserID],
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [Title],
    [CryptedPassword],
    [IsActive],
    [MarkDeleted],
    [TimeZoneID],
    [CultureName],
    [LastLogin],
    [LastActivity],
    [LastPing],
    [LastWaterCoolerID],
    [IsSystemAdmin],
    [IsFinanceAdmin],
    [IsPasswordExpired],
    [IsPortalUser],
    [IsChatUser],
    [PrimaryGroupID],
    [InOffice],
    [InOfficeComment],
    [ReceiveTicketNotifications],
    [ReceiveAllGroupNotifications],
    [SubscribeToNewTickets],
    [ActivatedOn],
    [DeactivatedOn],
    [OrganizationID],
    [LastVersion],
    [SessionID],
    [ImportID],
    [DateCreated],
    [DateModified],
    [CreatorID],
    [ModifierID],
    [OrgsUserCanSeeOnPortal],
    [DoNotAutoSubscribe],
    [IsClassicView],
    [SubscribeToNewActions],
    [ApprovedTerms],
    [ShowWelcomePage],
    [UserInformation],
    [PortalAutoReg],
    [AppChatID],
    [AppChatStatus],
    [MenuItems],
    [TicketRights],
    [Signature],
    [LinkedIn],
    [OnlyEmailAfterHours],
    [BlockInboundEmail],
    [SalesForceID],
    [ChangeTicketVisibility],
    [ChangeKBVisibility],
    [EnforceSingleSession],
    [NeedsIndexing],
    [AllowAnyTicketCustomer],
    [FontFamily],
    [FontSize],
    [CanCreateCompany],
    [CanEditCompany],
    [CanCreateContact],
    [CanEditContact],
    [RestrictUserFromEditingAnyActions],
    [AllowUserToEditAnyAction],
    [UserCanPinAction],
    [PortalLimitOrgTickets],
    [CanCreateAsset],
    [CanEditAsset],
    [CanChangeCommunityVisibility],
    [FilterInactive],
    [DisableExporting],
    [CanCreateProducts],
    [CanEditProducts],
    [CanCreateVersions],
    [CanEditVersions],
    [ReceiveUnassignedGroupEmails],
    [ProductFamiliesRights],
    [BlockEmailFromCreatingOnly]
  FROM [dbo].[Users]
  WHERE ([UserID] = @UserID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedInsertUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedInsertUser
GO

CREATE PROCEDURE dbo.uspGeneratedInsertUser

(
  @Email varchar(1024),
  @FirstName varchar(100),
  @MiddleName varchar(100),
  @LastName varchar(100),
  @Title varchar(100),
  @CryptedPassword varchar(255),
  @IsActive bit,
  @MarkDeleted bit,
  @TimeZoneID varchar(300),
  @CultureName varchar(50),
  @LastLogin datetime,
  @LastActivity datetime,
  @LastPing datetime,
  @LastWaterCoolerID int,
  @IsSystemAdmin bit,
  @IsFinanceAdmin bit,
  @IsPasswordExpired bit,
  @IsPortalUser bit,
  @IsChatUser bit,
  @PrimaryGroupID int,
  @InOffice bit,
  @InOfficeComment varchar(200),
  @ReceiveTicketNotifications bit,
  @ReceiveAllGroupNotifications bit,
  @SubscribeToNewTickets bit,
  @ActivatedOn datetime,
  @DeactivatedOn datetime,
  @OrganizationID int,
  @LastVersion varchar(50),
  @SessionID uniqueidentifier,
  @ImportID varchar(500),
  @DateCreated datetime,
  @DateModified datetime,
  @CreatorID int,
  @ModifierID int,
  @OrgsUserCanSeeOnPortal varchar(200),
  @DoNotAutoSubscribe bit,
  @IsClassicView bit,
  @SubscribeToNewActions bit,
  @ApprovedTerms bit,
  @ShowWelcomePage bit,
  @UserInformation varchar(MAX),
  @PortalAutoReg bit,
  @AppChatID varchar(200),
  @AppChatStatus bit,
  @MenuItems varchar(1000),
  @TicketRights int,
  @Signature varchar(MAX),
  @LinkedIn varchar(200),
  @OnlyEmailAfterHours bit,
  @BlockInboundEmail bit,
  @SalesForceID varchar(8000),
  @ChangeTicketVisibility bit,
  @ChangeKBVisibility bit,
  @EnforceSingleSession bit,
  @NeedsIndexing bit,
  @AllowAnyTicketCustomer bit,
  @FontFamily int,
  @FontSize int,
  @CanCreateCompany bit,
  @CanEditCompany bit,
  @CanCreateContact bit,
  @CanEditContact bit,
  @RestrictUserFromEditingAnyActions bit,
  @AllowUserToEditAnyAction bit,
  @UserCanPinAction bit,
  @PortalLimitOrgTickets bit,
  @CanCreateAsset bit,
  @CanEditAsset bit,
  @CanChangeCommunityVisibility bit,
  @FilterInactive bit,
  @DisableExporting bit,
  @CanCreateProducts bit,
  @CanEditProducts bit,
  @CanCreateVersions bit,
  @CanEditVersions bit,
  @ReceiveUnassignedGroupEmails bit,
  @ProductFamiliesRights int,
  @BlockEmailFromCreatingOnly bit,
  @Identity int OUT
)
AS
  SET NOCOUNT OFF;
  INSERT INTO [dbo].[Users]
  (
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [Title],
    [CryptedPassword],
    [IsActive],
    [MarkDeleted],
    [TimeZoneID],
    [CultureName],
    [LastLogin],
    [LastActivity],
    [LastPing],
    [LastWaterCoolerID],
    [IsSystemAdmin],
    [IsFinanceAdmin],
    [IsPasswordExpired],
    [IsPortalUser],
    [IsChatUser],
    [PrimaryGroupID],
    [InOffice],
    [InOfficeComment],
    [ReceiveTicketNotifications],
    [ReceiveAllGroupNotifications],
    [SubscribeToNewTickets],
    [ActivatedOn],
    [DeactivatedOn],
    [OrganizationID],
    [LastVersion],
    [SessionID],
    [ImportID],
    [DateCreated],
    [DateModified],
    [CreatorID],
    [ModifierID],
    [OrgsUserCanSeeOnPortal],
    [DoNotAutoSubscribe],
    [IsClassicView],
    [SubscribeToNewActions],
    [ApprovedTerms],
    [ShowWelcomePage],
    [UserInformation],
    [PortalAutoReg],
    [AppChatID],
    [AppChatStatus],
    [MenuItems],
    [TicketRights],
    [Signature],
    [LinkedIn],
    [OnlyEmailAfterHours],
    [BlockInboundEmail],
    [SalesForceID],
    [ChangeTicketVisibility],
    [ChangeKBVisibility],
    [EnforceSingleSession],
    [NeedsIndexing],
    [AllowAnyTicketCustomer],
    [FontFamily],
    [FontSize],
    [CanCreateCompany],
    [CanEditCompany],
    [CanCreateContact],
    [CanEditContact],
    [RestrictUserFromEditingAnyActions],
    [AllowUserToEditAnyAction],
    [UserCanPinAction],
    [PortalLimitOrgTickets],
    [CanCreateAsset],
    [CanEditAsset],
    [CanChangeCommunityVisibility],
    [FilterInactive],
    [DisableExporting],
    [CanCreateProducts],
    [CanEditProducts],
    [CanCreateVersions],
    [CanEditVersions],
    [ReceiveUnassignedGroupEmails],
    [ProductFamiliesRights],
    [BlockEmailFromCreatingOnly])
  VALUES (
    @Email,
    @FirstName,
    @MiddleName,
    @LastName,
    @Title,
    @CryptedPassword,
    @IsActive,
    @MarkDeleted,
    @TimeZoneID,
    @CultureName,
    @LastLogin,
    @LastActivity,
    @LastPing,
    @LastWaterCoolerID,
    @IsSystemAdmin,
    @IsFinanceAdmin,
    @IsPasswordExpired,
    @IsPortalUser,
    @IsChatUser,
    @PrimaryGroupID,
    @InOffice,
    @InOfficeComment,
    @ReceiveTicketNotifications,
    @ReceiveAllGroupNotifications,
    @SubscribeToNewTickets,
    @ActivatedOn,
    @DeactivatedOn,
    @OrganizationID,
    @LastVersion,
    @SessionID,
    @ImportID,
    @DateCreated,
    @DateModified,
    @CreatorID,
    @ModifierID,
    @OrgsUserCanSeeOnPortal,
    @DoNotAutoSubscribe,
    @IsClassicView,
    @SubscribeToNewActions,
    @ApprovedTerms,
    @ShowWelcomePage,
    @UserInformation,
    @PortalAutoReg,
    @AppChatID,
    @AppChatStatus,
    @MenuItems,
    @TicketRights,
    @Signature,
    @LinkedIn,
    @OnlyEmailAfterHours,
    @BlockInboundEmail,
    @SalesForceID,
    @ChangeTicketVisibility,
    @ChangeKBVisibility,
    @EnforceSingleSession,
    @NeedsIndexing,
    @AllowAnyTicketCustomer,
    @FontFamily,
    @FontSize,
    @CanCreateCompany,
    @CanEditCompany,
    @CanCreateContact,
    @CanEditContact,
    @RestrictUserFromEditingAnyActions,
    @AllowUserToEditAnyAction,
    @UserCanPinAction,
    @PortalLimitOrgTickets,
    @CanCreateAsset,
    @CanEditAsset,
    @CanChangeCommunityVisibility,
    @FilterInactive,
    @DisableExporting,
    @CanCreateProducts,
    @CanEditProducts,
    @CanCreateVersions,
    @CanEditVersions,
    @ReceiveUnassignedGroupEmails,
    @ProductFamiliesRights,
    @BlockEmailFromCreatingOnly)

SET @Identity = SCOPE_IDENTITY()
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedUpdateUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedUpdateUser
GO

CREATE PROCEDURE dbo.uspGeneratedUpdateUser

(
  @UserID int,
  @Email varchar(1024),
  @FirstName varchar(100),
  @MiddleName varchar(100),
  @LastName varchar(100),
  @Title varchar(100),
  @CryptedPassword varchar(255),
  @IsActive bit,
  @MarkDeleted bit,
  @TimeZoneID varchar(300),
  @CultureName varchar(50),
  @LastLogin datetime,
  @LastActivity datetime,
  @LastPing datetime,
  @LastWaterCoolerID int,
  @IsSystemAdmin bit,
  @IsFinanceAdmin bit,
  @IsPasswordExpired bit,
  @IsPortalUser bit,
  @IsChatUser bit,
  @PrimaryGroupID int,
  @InOffice bit,
  @InOfficeComment varchar(200),
  @ReceiveTicketNotifications bit,
  @ReceiveAllGroupNotifications bit,
  @SubscribeToNewTickets bit,
  @ActivatedOn datetime,
  @DeactivatedOn datetime,
  @OrganizationID int,
  @LastVersion varchar(50),
  @SessionID uniqueidentifier,
  @ImportID varchar(500),
  @DateModified datetime,
  @ModifierID int,
  @OrgsUserCanSeeOnPortal varchar(200),
  @DoNotAutoSubscribe bit,
  @IsClassicView bit,
  @SubscribeToNewActions bit,
  @ApprovedTerms bit,
  @ShowWelcomePage bit,
  @UserInformation varchar(MAX),
  @PortalAutoReg bit,
  @AppChatID varchar(200),
  @AppChatStatus bit,
  @MenuItems varchar(1000),
  @TicketRights int,
  @Signature varchar(MAX),
  @LinkedIn varchar(200),
  @OnlyEmailAfterHours bit,
  @BlockInboundEmail bit,
  @SalesForceID varchar(8000),
  @ChangeTicketVisibility bit,
  @ChangeKBVisibility bit,
  @EnforceSingleSession bit,
  @NeedsIndexing bit,
  @AllowAnyTicketCustomer bit,
  @FontFamily int,
  @FontSize int,
  @CanCreateCompany bit,
  @CanEditCompany bit,
  @CanCreateContact bit,
  @CanEditContact bit,
  @RestrictUserFromEditingAnyActions bit,
  @AllowUserToEditAnyAction bit,
  @UserCanPinAction bit,
  @PortalLimitOrgTickets bit,
  @CanCreateAsset bit,
  @CanEditAsset bit,
  @CanChangeCommunityVisibility bit,
  @FilterInactive bit,
  @DisableExporting bit,
  @CanCreateProducts bit,
  @CanEditProducts bit,
  @CanCreateVersions bit,
  @CanEditVersions bit,
  @ReceiveUnassignedGroupEmails bit,
  @ProductFamiliesRights int,
  @BlockEmailFromCreatingOnly bit
)
AS
  SET NOCOUNT OFF;
  UPDATE [dbo].[Users]
  SET
    [Email] = @Email,
    [FirstName] = @FirstName,
    [MiddleName] = @MiddleName,
    [LastName] = @LastName,
    [Title] = @Title,
    [CryptedPassword] = @CryptedPassword,
    [IsActive] = @IsActive,
    [MarkDeleted] = @MarkDeleted,
    [TimeZoneID] = @TimeZoneID,
    [CultureName] = @CultureName,
    [LastLogin] = @LastLogin,
    [LastActivity] = @LastActivity,
    [LastPing] = @LastPing,
    [LastWaterCoolerID] = @LastWaterCoolerID,
    [IsSystemAdmin] = @IsSystemAdmin,
    [IsFinanceAdmin] = @IsFinanceAdmin,
    [IsPasswordExpired] = @IsPasswordExpired,
    [IsPortalUser] = @IsPortalUser,
    [IsChatUser] = @IsChatUser,
    [PrimaryGroupID] = @PrimaryGroupID,
    [InOffice] = @InOffice,
    [InOfficeComment] = @InOfficeComment,
    [ReceiveTicketNotifications] = @ReceiveTicketNotifications,
    [ReceiveAllGroupNotifications] = @ReceiveAllGroupNotifications,
    [SubscribeToNewTickets] = @SubscribeToNewTickets,
    [ActivatedOn] = @ActivatedOn,
    [DeactivatedOn] = @DeactivatedOn,
    [OrganizationID] = @OrganizationID,
    [LastVersion] = @LastVersion,
    [SessionID] = @SessionID,
    [ImportID] = @ImportID,
    [DateModified] = @DateModified,
    [ModifierID] = @ModifierID,
    [OrgsUserCanSeeOnPortal] = @OrgsUserCanSeeOnPortal,
    [DoNotAutoSubscribe] = @DoNotAutoSubscribe,
    [IsClassicView] = @IsClassicView,
    [SubscribeToNewActions] = @SubscribeToNewActions,
    [ApprovedTerms] = @ApprovedTerms,
    [ShowWelcomePage] = @ShowWelcomePage,
    [UserInformation] = @UserInformation,
    [PortalAutoReg] = @PortalAutoReg,
    [AppChatID] = @AppChatID,
    [AppChatStatus] = @AppChatStatus,
    [MenuItems] = @MenuItems,
    [TicketRights] = @TicketRights,
    [Signature] = @Signature,
    [LinkedIn] = @LinkedIn,
    [OnlyEmailAfterHours] = @OnlyEmailAfterHours,
    [BlockInboundEmail] = @BlockInboundEmail,
    [SalesForceID] = @SalesForceID,
    [ChangeTicketVisibility] = @ChangeTicketVisibility,
    [ChangeKBVisibility] = @ChangeKBVisibility,
    [EnforceSingleSession] = @EnforceSingleSession,
    [NeedsIndexing] = @NeedsIndexing,
    [AllowAnyTicketCustomer] = @AllowAnyTicketCustomer,
    [FontFamily] = @FontFamily,
    [FontSize] = @FontSize,
    [CanCreateCompany] = @CanCreateCompany,
    [CanEditCompany] = @CanEditCompany,
    [CanCreateContact] = @CanCreateContact,
    [CanEditContact] = @CanEditContact,
    [RestrictUserFromEditingAnyActions] = @RestrictUserFromEditingAnyActions,
    [AllowUserToEditAnyAction] = @AllowUserToEditAnyAction,
    [UserCanPinAction] = @UserCanPinAction,
    [PortalLimitOrgTickets] = @PortalLimitOrgTickets,
    [CanCreateAsset] = @CanCreateAsset,
    [CanEditAsset] = @CanEditAsset,
    [CanChangeCommunityVisibility] = @CanChangeCommunityVisibility,
    [FilterInactive] = @FilterInactive,
    [DisableExporting] = @DisableExporting,
    [CanCreateProducts] = @CanCreateProducts,
    [CanEditProducts] = @CanEditProducts,
    [CanCreateVersions] = @CanCreateVersions,
    [CanEditVersions] = @CanEditVersions,
    [ReceiveUnassignedGroupEmails] = @ReceiveUnassignedGroupEmails,
    [ProductFamiliesRights] = @ProductFamiliesRights,
    [BlockEmailFromCreatingOnly] = @BlockEmailFromCreatingOnly
  WHERE ([UserID] = @UserID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedDeleteUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedDeleteUser
GO

CREATE PROCEDURE dbo.uspGeneratedDeleteUser

(
  @UserID int
)
AS
  SET NOCOUNT OFF;
  DELETE FROM [dbo].[Users]
  WHERE ([UserID] = @UserID)
GO


IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedSelectUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedSelectUser
GO

CREATE PROCEDURE dbo.uspGeneratedSelectUser

(
  @UserID int
)
AS
  SET NOCOUNT OFF;
  SELECT
    [UserID],
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [Title],
    [CryptedPassword],
    [IsActive],
    [MarkDeleted],
    [TimeZoneID],
    [CultureName],
    [LastLogin],
    [LastActivity],
    [LastPing],
    [LastWaterCoolerID],
    [IsSystemAdmin],
    [IsFinanceAdmin],
    [IsPasswordExpired],
    [IsPortalUser],
    [IsChatUser],
    [PrimaryGroupID],
    [InOffice],
    [InOfficeComment],
    [ReceiveTicketNotifications],
    [ReceiveAllGroupNotifications],
    [SubscribeToNewTickets],
    [ActivatedOn],
    [DeactivatedOn],
    [OrganizationID],
    [LastVersion],
    [SessionID],
    [ImportID],
    [DateCreated],
    [DateModified],
    [CreatorID],
    [ModifierID],
    [OrgsUserCanSeeOnPortal],
    [DoNotAutoSubscribe],
    [IsClassicView],
    [SubscribeToNewActions],
    [ApprovedTerms],
    [ShowWelcomePage],
    [UserInformation],
    [PortalAutoReg],
    [AppChatID],
    [AppChatStatus],
    [MenuItems],
    [TicketRights],
    [Signature],
    [LinkedIn],
    [OnlyEmailAfterHours],
    [BlockInboundEmail],
    [SalesForceID],
    [ChangeTicketVisibility],
    [ChangeKBVisibility],
    [EnforceSingleSession],
    [NeedsIndexing],
    [AllowAnyTicketCustomer],
    [FontFamily],
    [FontSize],
    [CanCreateCompany],
    [CanEditCompany],
    [CanCreateContact],
    [CanEditContact],
    [RestrictUserFromEditingAnyActions],
    [AllowUserToEditAnyAction],
    [UserCanPinAction],
    [PortalLimitOrgTickets],
    [CanCreateAsset],
    [CanEditAsset],
    [CanChangeCommunityVisibility],
    [FilterInactive],
    [DisableExporting],
    [CanCreateProducts],
    [CanEditProducts],
    [CanCreateVersions],
    [CanEditVersions],
    [ReceiveUnassignedGroupEmails],
    [ProductFamiliesRights],
    [BlockEmailFromCreatingOnly]
  FROM [dbo].[Users]
  WHERE ([UserID] = @UserID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedInsertUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedInsertUser
GO

CREATE PROCEDURE dbo.uspGeneratedInsertUser

(
  @Email varchar(1024),
  @FirstName varchar(100),
  @MiddleName varchar(100),
  @LastName varchar(100),
  @Title varchar(100),
  @CryptedPassword varchar(255),
  @IsActive bit,
  @MarkDeleted bit,
  @TimeZoneID varchar(300),
  @CultureName varchar(50),
  @LastLogin datetime,
  @LastActivity datetime,
  @LastPing datetime,
  @LastWaterCoolerID int,
  @IsSystemAdmin bit,
  @IsFinanceAdmin bit,
  @IsPasswordExpired bit,
  @IsPortalUser bit,
  @IsChatUser bit,
  @PrimaryGroupID int,
  @InOffice bit,
  @InOfficeComment varchar(200),
  @ReceiveTicketNotifications bit,
  @ReceiveAllGroupNotifications bit,
  @SubscribeToNewTickets bit,
  @ActivatedOn datetime,
  @DeactivatedOn datetime,
  @OrganizationID int,
  @LastVersion varchar(50),
  @SessionID uniqueidentifier,
  @ImportID varchar(500),
  @DateCreated datetime,
  @DateModified datetime,
  @CreatorID int,
  @ModifierID int,
  @OrgsUserCanSeeOnPortal varchar(200),
  @DoNotAutoSubscribe bit,
  @IsClassicView bit,
  @SubscribeToNewActions bit,
  @ApprovedTerms bit,
  @ShowWelcomePage bit,
  @UserInformation varchar(MAX),
  @PortalAutoReg bit,
  @AppChatID varchar(200),
  @AppChatStatus bit,
  @MenuItems varchar(1000),
  @TicketRights int,
  @Signature varchar(MAX),
  @LinkedIn varchar(200),
  @OnlyEmailAfterHours bit,
  @BlockInboundEmail bit,
  @SalesForceID varchar(8000),
  @ChangeTicketVisibility bit,
  @ChangeKBVisibility bit,
  @EnforceSingleSession bit,
  @NeedsIndexing bit,
  @AllowAnyTicketCustomer bit,
  @FontFamily int,
  @FontSize int,
  @CanCreateCompany bit,
  @CanEditCompany bit,
  @CanCreateContact bit,
  @CanEditContact bit,
  @RestrictUserFromEditingAnyActions bit,
  @AllowUserToEditAnyAction bit,
  @UserCanPinAction bit,
  @PortalLimitOrgTickets bit,
  @CanCreateAsset bit,
  @CanEditAsset bit,
  @CanChangeCommunityVisibility bit,
  @FilterInactive bit,
  @DisableExporting bit,
  @CanCreateProducts bit,
  @CanEditProducts bit,
  @CanCreateVersions bit,
  @CanEditVersions bit,
  @ReceiveUnassignedGroupEmails bit,
  @ProductFamiliesRights int,
  @BlockEmailFromCreatingOnly bit,
  @Identity int OUT
)
AS
  SET NOCOUNT OFF;
  INSERT INTO [dbo].[Users]
  (
    [Email],
    [FirstName],
    [MiddleName],
    [LastName],
    [Title],
    [CryptedPassword],
    [IsActive],
    [MarkDeleted],
    [TimeZoneID],
    [CultureName],
    [LastLogin],
    [LastActivity],
    [LastPing],
    [LastWaterCoolerID],
    [IsSystemAdmin],
    [IsFinanceAdmin],
    [IsPasswordExpired],
    [IsPortalUser],
    [IsChatUser],
    [PrimaryGroupID],
    [InOffice],
    [InOfficeComment],
    [ReceiveTicketNotifications],
    [ReceiveAllGroupNotifications],
    [SubscribeToNewTickets],
    [ActivatedOn],
    [DeactivatedOn],
    [OrganizationID],
    [LastVersion],
    [SessionID],
    [ImportID],
    [DateCreated],
    [DateModified],
    [CreatorID],
    [ModifierID],
    [OrgsUserCanSeeOnPortal],
    [DoNotAutoSubscribe],
    [IsClassicView],
    [SubscribeToNewActions],
    [ApprovedTerms],
    [ShowWelcomePage],
    [UserInformation],
    [PortalAutoReg],
    [AppChatID],
    [AppChatStatus],
    [MenuItems],
    [TicketRights],
    [Signature],
    [LinkedIn],
    [OnlyEmailAfterHours],
    [BlockInboundEmail],
    [SalesForceID],
    [ChangeTicketVisibility],
    [ChangeKBVisibility],
    [EnforceSingleSession],
    [NeedsIndexing],
    [AllowAnyTicketCustomer],
    [FontFamily],
    [FontSize],
    [CanCreateCompany],
    [CanEditCompany],
    [CanCreateContact],
    [CanEditContact],
    [RestrictUserFromEditingAnyActions],
    [AllowUserToEditAnyAction],
    [UserCanPinAction],
    [PortalLimitOrgTickets],
    [CanCreateAsset],
    [CanEditAsset],
    [CanChangeCommunityVisibility],
    [FilterInactive],
    [DisableExporting],
    [CanCreateProducts],
    [CanEditProducts],
    [CanCreateVersions],
    [CanEditVersions],
    [ReceiveUnassignedGroupEmails],
    [ProductFamiliesRights],
    [BlockEmailFromCreatingOnly])
  VALUES (
    @Email,
    @FirstName,
    @MiddleName,
    @LastName,
    @Title,
    @CryptedPassword,
    @IsActive,
    @MarkDeleted,
    @TimeZoneID,
    @CultureName,
    @LastLogin,
    @LastActivity,
    @LastPing,
    @LastWaterCoolerID,
    @IsSystemAdmin,
    @IsFinanceAdmin,
    @IsPasswordExpired,
    @IsPortalUser,
    @IsChatUser,
    @PrimaryGroupID,
    @InOffice,
    @InOfficeComment,
    @ReceiveTicketNotifications,
    @ReceiveAllGroupNotifications,
    @SubscribeToNewTickets,
    @ActivatedOn,
    @DeactivatedOn,
    @OrganizationID,
    @LastVersion,
    @SessionID,
    @ImportID,
    @DateCreated,
    @DateModified,
    @CreatorID,
    @ModifierID,
    @OrgsUserCanSeeOnPortal,
    @DoNotAutoSubscribe,
    @IsClassicView,
    @SubscribeToNewActions,
    @ApprovedTerms,
    @ShowWelcomePage,
    @UserInformation,
    @PortalAutoReg,
    @AppChatID,
    @AppChatStatus,
    @MenuItems,
    @TicketRights,
    @Signature,
    @LinkedIn,
    @OnlyEmailAfterHours,
    @BlockInboundEmail,
    @SalesForceID,
    @ChangeTicketVisibility,
    @ChangeKBVisibility,
    @EnforceSingleSession,
    @NeedsIndexing,
    @AllowAnyTicketCustomer,
    @FontFamily,
    @FontSize,
    @CanCreateCompany,
    @CanEditCompany,
    @CanCreateContact,
    @CanEditContact,
    @RestrictUserFromEditingAnyActions,
    @AllowUserToEditAnyAction,
    @UserCanPinAction,
    @PortalLimitOrgTickets,
    @CanCreateAsset,
    @CanEditAsset,
    @CanChangeCommunityVisibility,
    @FilterInactive,
    @DisableExporting,
    @CanCreateProducts,
    @CanEditProducts,
    @CanCreateVersions,
    @CanEditVersions,
    @ReceiveUnassignedGroupEmails,
    @ProductFamiliesRights,
    @BlockEmailFromCreatingOnly)

SET @Identity = SCOPE_IDENTITY()
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedUpdateUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedUpdateUser
GO

CREATE PROCEDURE dbo.uspGeneratedUpdateUser

(
  @UserID int,
  @Email varchar(1024),
  @FirstName varchar(100),
  @MiddleName varchar(100),
  @LastName varchar(100),
  @Title varchar(100),
  @CryptedPassword varchar(255),
  @IsActive bit,
  @MarkDeleted bit,
  @TimeZoneID varchar(300),
  @CultureName varchar(50),
  @LastLogin datetime,
  @LastActivity datetime,
  @LastPing datetime,
  @LastWaterCoolerID int,
  @IsSystemAdmin bit,
  @IsFinanceAdmin bit,
  @IsPasswordExpired bit,
  @IsPortalUser bit,
  @IsChatUser bit,
  @PrimaryGroupID int,
  @InOffice bit,
  @InOfficeComment varchar(200),
  @ReceiveTicketNotifications bit,
  @ReceiveAllGroupNotifications bit,
  @SubscribeToNewTickets bit,
  @ActivatedOn datetime,
  @DeactivatedOn datetime,
  @OrganizationID int,
  @LastVersion varchar(50),
  @SessionID uniqueidentifier,
  @ImportID varchar(500),
  @DateModified datetime,
  @ModifierID int,
  @OrgsUserCanSeeOnPortal varchar(200),
  @DoNotAutoSubscribe bit,
  @IsClassicView bit,
  @SubscribeToNewActions bit,
  @ApprovedTerms bit,
  @ShowWelcomePage bit,
  @UserInformation varchar(MAX),
  @PortalAutoReg bit,
  @AppChatID varchar(200),
  @AppChatStatus bit,
  @MenuItems varchar(1000),
  @TicketRights int,
  @Signature varchar(MAX),
  @LinkedIn varchar(200),
  @OnlyEmailAfterHours bit,
  @BlockInboundEmail bit,
  @SalesForceID varchar(8000),
  @ChangeTicketVisibility bit,
  @ChangeKBVisibility bit,
  @EnforceSingleSession bit,
  @NeedsIndexing bit,
  @AllowAnyTicketCustomer bit,
  @FontFamily int,
  @FontSize int,
  @CanCreateCompany bit,
  @CanEditCompany bit,
  @CanCreateContact bit,
  @CanEditContact bit,
  @RestrictUserFromEditingAnyActions bit,
  @AllowUserToEditAnyAction bit,
  @UserCanPinAction bit,
  @PortalLimitOrgTickets bit,
  @CanCreateAsset bit,
  @CanEditAsset bit,
  @CanChangeCommunityVisibility bit,
  @FilterInactive bit,
  @DisableExporting bit,
  @CanCreateProducts bit,
  @CanEditProducts bit,
  @CanCreateVersions bit,
  @CanEditVersions bit,
  @ReceiveUnassignedGroupEmails bit,
  @ProductFamiliesRights int,
  @BlockEmailFromCreatingOnly bit
)
AS
  SET NOCOUNT OFF;
  UPDATE [dbo].[Users]
  SET
    [Email] = @Email,
    [FirstName] = @FirstName,
    [MiddleName] = @MiddleName,
    [LastName] = @LastName,
    [Title] = @Title,
    [CryptedPassword] = @CryptedPassword,
    [IsActive] = @IsActive,
    [MarkDeleted] = @MarkDeleted,
    [TimeZoneID] = @TimeZoneID,
    [CultureName] = @CultureName,
    [LastLogin] = @LastLogin,
    [LastActivity] = @LastActivity,
    [LastPing] = @LastPing,
    [LastWaterCoolerID] = @LastWaterCoolerID,
    [IsSystemAdmin] = @IsSystemAdmin,
    [IsFinanceAdmin] = @IsFinanceAdmin,
    [IsPasswordExpired] = @IsPasswordExpired,
    [IsPortalUser] = @IsPortalUser,
    [IsChatUser] = @IsChatUser,
    [PrimaryGroupID] = @PrimaryGroupID,
    [InOffice] = @InOffice,
    [InOfficeComment] = @InOfficeComment,
    [ReceiveTicketNotifications] = @ReceiveTicketNotifications,
    [ReceiveAllGroupNotifications] = @ReceiveAllGroupNotifications,
    [SubscribeToNewTickets] = @SubscribeToNewTickets,
    [ActivatedOn] = @ActivatedOn,
    [DeactivatedOn] = @DeactivatedOn,
    [OrganizationID] = @OrganizationID,
    [LastVersion] = @LastVersion,
    [SessionID] = @SessionID,
    [ImportID] = @ImportID,
    [DateModified] = @DateModified,
    [ModifierID] = @ModifierID,
    [OrgsUserCanSeeOnPortal] = @OrgsUserCanSeeOnPortal,
    [DoNotAutoSubscribe] = @DoNotAutoSubscribe,
    [IsClassicView] = @IsClassicView,
    [SubscribeToNewActions] = @SubscribeToNewActions,
    [ApprovedTerms] = @ApprovedTerms,
    [ShowWelcomePage] = @ShowWelcomePage,
    [UserInformation] = @UserInformation,
    [PortalAutoReg] = @PortalAutoReg,
    [AppChatID] = @AppChatID,
    [AppChatStatus] = @AppChatStatus,
    [MenuItems] = @MenuItems,
    [TicketRights] = @TicketRights,
    [Signature] = @Signature,
    [LinkedIn] = @LinkedIn,
    [OnlyEmailAfterHours] = @OnlyEmailAfterHours,
    [BlockInboundEmail] = @BlockInboundEmail,
    [SalesForceID] = @SalesForceID,
    [ChangeTicketVisibility] = @ChangeTicketVisibility,
    [ChangeKBVisibility] = @ChangeKBVisibility,
    [EnforceSingleSession] = @EnforceSingleSession,
    [NeedsIndexing] = @NeedsIndexing,
    [AllowAnyTicketCustomer] = @AllowAnyTicketCustomer,
    [FontFamily] = @FontFamily,
    [FontSize] = @FontSize,
    [CanCreateCompany] = @CanCreateCompany,
    [CanEditCompany] = @CanEditCompany,
    [CanCreateContact] = @CanCreateContact,
    [CanEditContact] = @CanEditContact,
    [RestrictUserFromEditingAnyActions] = @RestrictUserFromEditingAnyActions,
    [AllowUserToEditAnyAction] = @AllowUserToEditAnyAction,
    [UserCanPinAction] = @UserCanPinAction,
    [PortalLimitOrgTickets] = @PortalLimitOrgTickets,
    [CanCreateAsset] = @CanCreateAsset,
    [CanEditAsset] = @CanEditAsset,
    [CanChangeCommunityVisibility] = @CanChangeCommunityVisibility,
    [FilterInactive] = @FilterInactive,
    [DisableExporting] = @DisableExporting,
    [CanCreateProducts] = @CanCreateProducts,
    [CanEditProducts] = @CanEditProducts,
    [CanCreateVersions] = @CanCreateVersions,
    [CanEditVersions] = @CanEditVersions,
    [ReceiveUnassignedGroupEmails] = @ReceiveUnassignedGroupEmails,
    [ProductFamiliesRights] = @ProductFamiliesRights,
    [BlockEmailFromCreatingOnly] = @BlockEmailFromCreatingOnly
  WHERE ([UserID] = @UserID)
GO

IF EXISTS (SELECT * FROM sysobjects WHERE name = 'uspGeneratedDeleteUser' AND user_name(uid) = 'dbo')	DROP PROCEDURE dbo.uspGeneratedDeleteUser
GO

CREATE PROCEDURE dbo.uspGeneratedDeleteUser

(
  @UserID int
)
AS
  SET NOCOUNT OFF;
  DELETE FROM [dbo].[Users]
  WHERE ([UserID] = @UserID)
GO


